### ISSUE TITLE
Can not start TTS addons

### ISSUE THREAD

**Issue by rp3tya** [Poeschl/Hassio-Addons#106]
**Which addon?**
MaryTTS

**Describe the bug**
Addon exits soon after start.

**To Reproduce**
Installed the addon and clicked Start, then inspected Log tab.

**Expected behavior**
Addon is running, services are started.

**Screenshots**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cmd] /bin/ash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**System**
* Raspberry Pi 4
* Home Assistant 0.116.2
* Supervisor version: 247
* Host system version: HassOS 4.13

**Comment by rumpledawf** [comment]
I have the exact same setup and issue.

**Comment by Poeschl** [comment]
I updated the maryTTS addon. The updated addon is available in the `marytts-bugfix` branch. Could you test the new version if its working also for you?

Download the folder of the addon an put it in the `/addon` folder. Open the config.json and remove the `image:` line. In the Supervisor Addon store, click refresh and build the local addon.

**Comment by rp3tya** [comment]
Log output with specified branch looks better, but the container still stops after a few seconds:
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:05:54] INFO: Setup voice
[14:05:54] INFO: Start MaryTTS
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (Alpine 8.252.09-r0)
OpenJDK Zero VM (build 25.252-b09, interpreted mode)
```

Maybe worth to mention that the initial report applies to PicoTTS addon as well.

**Comment by rp3tya** [comment]
Correction to above: although the addon appears to be stopped, after a few minutes MaryTTS was reachable through its web interface (local addon, updated branch).

**Comment by Poeschl** [comment]
MaryTTS as well as picoTTS will take some time to start.
I might add a little notice in the log about it. Thanks for testing the branch ;)

**Comment by Poeschl** [comment]
I also updated the picoTTS addon. Would you be so kind and test it also?

**Comment by rp3tya** [comment]
Cool, picoTTS also works with the update.

**Comment by Poeschl** [comment]
Nice, then I will merge the changes, and the offical addons will get an update during the next half hour.
