### ISSUE TITLE
More logging for MPD addon

### ISSUE THREAD

**Issue by tdesplenter** [Poeschl/Hassio-Addons#116]
**Which addon?**
MPD

**Is your feature request related to a problem? Please describe.**
MPD addon starts and stops without any errors in the log *(except the RTIOThread one)*.

**Describe the solution you'd like**
More logging, so I can hopefully figure out what's going on.

**Describe alternatives you've considered**
Updated to the latest version (1.4.0); Restarted HA; Uninstalled & re-installed MPD addon. Issue persists.

**Additional context**
My log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd-permissions: applying... 
[fix-attrs.d] mpd-permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
[11:13:13] INFO: Setup Folders
[cont-init.d] setup-folders: exited 0.
[cont-init.d] setup-settings: executing... 
[11:13:13] INFO: Setup settings
[cont-init.d] setup-settings: exited 0.
[cont-init.d] done.
[services.d] starting services
[11:13:13] INFO: Start MPD
[services.d] done.
[cmd] /bin/ash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
[s6-finish] sending all processes the TERM signal.
```

**System info**

Raspberry Pi 4
Home Assistant 0.116.4
HassOS 5.2 (dev branch; was needed to support boot-from-usb)
Supervisor 249

**Comment by Poeschl** [comment]
A verbose option will be added with version `1.4.1`. For more custom settings the custom config file is also an option.

**Comment by Poeschl** [comment]
Will be delayed, due a build system failure....
