### ISSUE TITLE
[MPD] Make http as audio_output available

### ISSUE THREAD

**Issue by koengithub** [Poeschl/Hassio-Addons#127]
**Which addon?**
MPD

**Is your feature request related to a problem? Please describe.**
When I enable httpd in the .conf file as audio_output, I can't test this because the port (default = 8000) isn't available to the docker container

**Describe the solution you'd like**
open an extra port for httpd

**Describe alternatives you've considered**
Maybe an extra httpd option as audio output in the configuration panel ?

**Additional context**
audio_output {
	type		"httpd"
	name		"My HTTP Stream"
	encoder		"vorbis"	
	port		"8000"
	bind_to_address	"0.0.0.0"		
	quality		"5.0"			
	bitrate		"192"		
	format		"44100:16:1"
	max_clients	"5"		
}

**Comment by Poeschl** [comment]
I implemented a default httpd output on a specified port. If the settings are not sufficient for your setup, use your custom config.

**Comment by koengithub** [comment]
Thanks a lot !
