### ISSUE TITLE
[Valetudo-Mapper] Update of the MQTT configuration in order to be recognized in device and not only an entity

### ISSUE THREAD

**Issue by dckiller51** [Poeschl/Hassio-Addons#134]
**Which addon?**
valetudo-mapper

**Is your feature request related to a problem? Please describe.**

No this is not a problem but related to the MQTT configuration. Can you add Device so that it is attached to Vacuum

**Describe the solution you'd like**
device: { manufacturer: "Roborock", name: this.identifier, identifiers: [ this.identifier ] },

![Sans titre](https://user-images.githubusercontent.com/53062806/100226814-8adb0300-2f20-11eb-81cd-d9aa64a6a3ab.png)
![Sans titre1](https://user-images.githubusercontent.com/53062806/100226816-8b739980-2f20-11eb-8819-e9b26ac6ba55.png)
![Sans titre3](https://user-images.githubusercontent.com/53062806/100226817-8c0c3000-2f20-11eb-9110-5aa73109eb87.png)

**Comment by Poeschl** [comment]
For this the mqtt autodiscovery message needs to be changed. Since the addon only contains the binary of Valetudo-Mapper the repository of it might be the place to ask for the change.

https://github.com/rand256/valetudo-mapper

**Comment by dckiller51** [comment]
I'll ask then. I have already asked him about the vacuum cleaner something he did. Thank you

**Comment by dckiller51** [comment]
Finally, this does not work despite the update of RAND256

MAJ MQTT: [https://github.com/rand256/valetudo-mapper/blob/master/lib/MqttClient.js](url)

````
    this.autoconf_payloads = {
        map: {
            name: this.identifier + "_map",
            unique_id: this.identifier + "_map",
            device: { manufacturer: "Roborock", name: this.identifier, identifiers: [ this.identifier ] },
            topic: this.topics.map
        }
    };
````
MQTT message:

````
{
  "name": "xiaomi_vacuum_cleaner_map",
  "unique_id": "xiaomi_vacuum_cleaner_map",
  "topic": "valetudo/xiaomi_vacuum_cleaner/map"
}
````

[https://developers.home-assistant.io/docs/device_registry_index/](url)

**Comment by Poeschl** [comment]
The addon needs to be updated, to also use the new commit. Will be done in the next days.
