### ISSUE TITLE
[Valetudo-Mapper] Config fails to save in 1.6.0

### ISSUE THREAD

**Issue by GergoIO** [Poeschl/Hassio-Addons#137]
**Which addon?**
Valetudo Mapper

**Describe the bug**
Unable to save configuration after update to version 1.6.0

**To Reproduce**
Update to 1.6.0
Try to save configuration (even modifying a single option from false to true in the default config fails to save)

**Expected behavior**
Config saves

**Screenshots**
Version 1.6.0
![valetudo mapper](https://user-images.githubusercontent.com/61317134/100480924-9417cb80-30ea-11eb-8c6d-4e83134479ed.PNG)

Working in previous version: 1.5.0
![image](https://user-images.githubusercontent.com/61317134/100481104-143e3100-30eb-11eb-9343-afe4a8caca33.png)

**System**

* Supervisor version: 2020.11.0

* Host system version
0.118.4
--
Installation Type | Home Assistant Supervised

**Errors reported in 1.6.0**:

20-11-27 19:56:51 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 243ffc37_valetudomapper!
20-11-27 19:56:51 ERROR (MainThread) [supervisor.addons.addon] Add-on 243ffc37_valetudomapper has invalid options: not a valid value. Got {'mapSettings': {'drawPath': True, 'drawCharger': True, 'drawRobot': True, 'drawCurrentlyCleanedZones': False, 'drawCurrentlyCleanedBlocks': False, 'drawForbiddenZones': True, 'drawVirtualWalls': True, 'scale': 4, 'gradientBackground': True, 'autoCrop': 20, 'rotate': False}, 'mapColors': {}, 'mqtt': {'identifier': 'rockrobo', 'topicPrefix': 'valetudo', 'autoconfPrefix': 'homeassistant', 'broker_url': 'mqtt://user:pass@foobar.example', 'caPath': '', 'mapDataTopic': 'valetudo/rockrobo/map_data'...
20-11-27 19:56:51 ERROR (MainThread) [supervisor.misc.tasks] 243ffc37_valetudomapper watchdog reanimation failed with 

Hope that's clear, let me know if you need any other info.
Thanks

**Comment by Poeschl** [comment]
Investigating...

**Comment by kotarokun** [comment]
I want to install Valetudo Mapper but I get the Same problem.
I just change my IP to: 'mqtt//192.179.***.**:1883'
Also without port i get these errors...
`Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'/mapSettings': {'drawPath': True, 'drawCharger': True, 'drawRobot': True, 'drawCurrentlyCleanedZones': False, 'drawCurrentlyCleanedBlocks': False, 'drawForbiddenZones': True, 'drawVirtualWalls': True, 'scale': 4, 'gradientBackground': True, 'autoCrop': 20}, 'mapColors': {}, 'mqtt': {'identifier': 'rockrobo', 'topicPrefix': 'valetudo', 'autoconfPrefix': 'homeassistant', 'broker_url': 'mqtt://192.168.179.34', 'caPath': '', 'mapDataTopic': 'valetudo/rockrobo/map_data', 'minMillisecondsBetweenM...`

**Comment by Poeschl** [comment]
@kotarokun Please open a new issue. Comments on old ones are hard to notice.

The port is mandatory in the brokers address.
