### ISSUE TITLE
Update Mopidy base image

### ISSUE THREAD

**Issue by Poeschl** [Poeschl/Hassio-Addons#14]
**Which addon?**
Mopidy

**Describe the solution you'd like**
Update the base image from stretch to `homeassistant/{arch]-base-debian:buster`.

Can be done when https://github.com/home-assistant/hassio-base/issues/37 is closed.

**Comment by apurvabhandari** [comment]
What exactly need to do?

**Comment by Poeschl** [comment]
The docker base image needs to be changed to Debian buster. Unfortunately this docker image is still missing

**Comment by apurvabhandari** [comment]
which Debian buster architecture or any ?

**Comment by Poeschl** [comment]
All of them

**Comment by Poeschl** [comment]
I might be a little short on explanation the last days. Sry about that.

What this issue is about:
Change the base image to `homeassistant/*-base-debian:buster` for mopidy and also use the latest packages.

**Comment by Poeschl** [comment]
closed by #24

**Comment by apurvabhandari** [comment]
can you check ?
docker pull apurvbhandari/hassio-mopidy-debian

**Comment by Poeschl** [comment]
I can't access your docker file for some reason.
The common way of requesting a check and contribution of your changes would be a pull request. 😉

Unfortunately this issue was already solved yesterday. 😢
