### ISSUE TITLE
Hassio-Addons/ICantBelieveItsNotValetudo: invalid background in case of using side panel

### ISSUE THREAD

**Issue by slydiman** [Poeschl/Hassio-Addons#142]
**Which addon?**
ICantBelieveItsNotValetudo

**Describe the bug**
Invalid (white) background in case of using the side panel.

**To Reproduce**
1. Select a dark theme
2. Enable "Show in sidebar"
3. Click "Valetudo Floorplan" on the sidebar

**Expected behavior**
A dark background exactly as in case of opening via the button "Open Web UI".

**Screenshots**
Bug:
http://slydiman.me/_t/valetudo_map_bug1.jpg

Expected background:
http://slydiman.me/_t/valetudo_map_bug2.jpg
http://slydiman.me/_t/valetudo_map_bug3.jpg

**System**
* Supervisor version: 2020.12.6
* Host system version: HA 0.118.5 on Raspberry PI4 (Raspbian GNU/Linux 10 (buster))

**Comment by Poeschl** [comment]
Looked into it and found out that the background is colored from HA directly. On the addon page it is colored through the `hass-subpage` tag. On the sidepanel iframe, this tag is not present and the background gets not colored correctly.

The addon is only serving the image and has no way to change the appearance of the ingress page. I noticed that the [dark theme of slate](https://github.com/seangreen2/slate_theme) does handle the background correctly by styling the iframe correctly. This could be a starting point for bringing the issue up directly on the HA repository.

**Comment by slydiman** [comment]
I have used the dark theme slate - nothing changed.
The browser is the latest Google Chrome on Windows 10 with the dark theme.
I can open the image in the separate tab and it looks ok
http://slydiman.me/_t/valetudo_map_bug4.jpg
I opened the image using the button "Open Web UI" and I can control the background unchecking --primary-background-color
http://slydiman.me/_t/valetudo_map_bug5.jpg
http://slydiman.me/_t/valetudo_map_bug6.jpg
But using the button "Valetudo Floorplan" on the sidebar --primary-background-color is stay the same and does not affect the background:
!(http://slydiman.me/_t/valetudo_map_bug7.jpg)
No idea what is wrong.

**Comment by Poeschl** [comment]
I also intended to center the generated floor map on the addon page, so that may be the time to do this as well. I will take care 'bout it soon.

**Comment by Poeschl** [comment]
After the image is build on the master branch (about 30 minutes) the floorplan should be centered and having the correct background.

Please close the issue if so ;)

**Comment by slydiman** [comment]
Excellent!
