### ISSUE TITLE
[mpd] Add setting for the database root folder.

### ISSUE THREAD

**Issue by Poeschl** [Poeschl/Hassio-Addons#152]
**Which addon?**
mpd

**Is your feature request related to a problem? Please describe.**
Specify an own folder for the mpd database root folder setting. Media and Share volumes are already mapped.
Currently the setting is fixed to `/share/mpd/music`

**Describe the solution you'd like**
An optional setting like:

```yaml
media_folder: /media/music
```

see also #151

**Comment by LiJu09** [comment]
@Poeschl is #208 ok?
