### ISSUE TITLE
[pigpio] Can't initialise pigpio library

### ISSUE THREAD

**Issue by netwrkx** [Poeschl/Hassio-Addons#155]
**Which addon?**
pigpio

**Describe the bug**
[17:14:22] INFO: Started pigpio
2020-12-29 17:14:22 initPeripherals: mmap gpio failed (Operation not permitted)
Can't initialise pigpio library

**To Reproduce**

**Screenshots**
![screenshot1](https://user-images.githubusercontent.com/5035044/103298313-5ca68280-49fa-11eb-8fc3-70edccbe2dcf.PNG)
![screenshot2](https://user-images.githubusercontent.com/5035044/103298316-616b3680-49fa-11eb-9a20-ea173be60ee0.PNG)
![screenshot3](https://user-images.githubusercontent.com/5035044/103298342-6a5c0800-49fa-11eb-9407-b4245e6e2241.PNG)

**System**
* Supervisor version: 2020.12.7
* Host system version: Home Assistant OS 5.9
* Channel: stable
* Deployment: production

**Comment by Poeschl** [comment]
Which device does your system run on?

**Comment by netwrkx** [comment]
Raspberry 3b+

**Comment by Poeschl** [comment]
I assume the 64bit version of the host system?

**Comment by Poeschl** [comment]
Just saw a  new version  of pigpio which address this issue. I will update the addon tomorrow morning.

**Comment by DE29-87EE** [comment]
bonsoir , 
lorsque j'ai écrit la commande : sudo pigpiod 
il a affiché ce erreur : 2023-04-07 18:58:18 initPeripherals: mmap gpio failed (Operation not permitted)
Can't initialise pigpio library
s'ils vous plait aider moi
