### ISSUE TITLE
[ICantBeliveItsNotValetudo] broker_url regex does not allow value `core_mosquitto`

### ISSUE THREAD

**Issue by moritzgloeckl** [Poeschl/Hassio-Addons#158]
**Which addon?**
ICantBelieveItsNotValetudo

**Describe the bug**
The `readme.md` states:

> If you use the Mosquitto Addon in Home Assistant core_mosquitto can be used as broker address.

Using `'core_mosquitto'` as a value for `broker_url` results in error:

> Failed to save addon configuration, not a valid value for dictionary value @ data['options']. Got {'mapSettings': {'drawPath': True, 'drawCharger': True, 'drawRobot': True, 'scale': 4, 'rotate': 0}, 'mapColors': {'floor': '#0076ff', 'obstacle_weak': '#6699ff', 'obstacle_strong': '#52aeff', 'path': '#ffffff'}, 'mqtt': {'identifier': 'rockrobo', 'topicPrefix': 'valetudo', 'autoconfPrefix': 'homeassistant', 'broker_url': 'core_mosquitto', 'caPath': '', 'mapDataTopic': 'valetudo/rockrobo/map_data', 'minMillisecondsBetweenMapUpdates': 10000, 'publishMapImage': True}}

**To Reproduce**
1. Enter `'core_mosquitto'` as a value for `broker_url` in Configuration
2. Press SAVE

**Expected behavior**
Saving should work when value `core_mosquitto` is given.

**Comment by Poeschl** [comment]
The broker url needs to be specified completely. For example: `mqtt://<user>:<password>@core-mosquitto`

**Comment by moritzgloeckl** [comment]
Just created a PR to better document this issue.
