### ISSUE TITLE
Ngrok Client Install Error

### ISSUE THREAD

**Issue by ustunsoz** [Poeschl/Hassio-Addons#169]
**Which addon?**
Ngrok Client

**Describe the bug**
Failed to install addon
404 Client Error for http+docker://localhost/v1.40/images/create?tag=2.1.5&fromImage=thepicklenat0r%2Farmv7-hassio-ngrok: Not Found ("manifest for thepicklenat0r/armv7-hassio-ngrok:2.1.5 not found: manifest unknown: manifest unknown")

**To Reproduce**
1. Go to 'AddOn Store'
2. Click on 'Ngrok Client'
3. Scroll down to '.Install'

**System**

* Supervisor version: supervisor-2021.01.4 
* Host system version:  core-2021.1.4

**Comment by Poeschl** [comment]
It seems that you got the wrong repository 😉

This might be the place for the ngrok Addon: https://github.com/ThePicklenat0r/hassio-addons/issues

**Comment by ustunsoz** [comment]
I am Sorry

**Comment by Poeschl** [comment]
All good 😉 have a nice sunday.
