### ISSUE TITLE
"manifest not found"

### ISSUE THREAD

**Issue by oakcottage** [Poeschl/Hassio-Addons#17]
**Which addon?**
PicoTTS

**Describe the bug**
19-10-08 04:07:25 ERROR (SyncWorker_9) [hassio.docker.interface] Can't install poeschl/hassio-picotts-armv7:1.0-2 -> 404 Client Error: Not Found ("manifest for poeschl/hassio-picotts-armv7:1.0-2 not found").

**To Reproduce**
1. Go to Add-On Store in  Hassio Menu
2. Click on Install for PicoTTS (v1.0-2)
3. Error appears in system log

**Expected behavior**
PicoTTS should install

**Comment by Poeschl** [comment]
Seems the image for armv7 is not available. Will look into it.

**Comment by Poeschl** [comment]
Should be solved as soon the [build](https://travis-ci.org/Poeschl/Hassio-Addons/jobs/598293920) finishes.

If the addon starts correctly, feel free to close the issue.

**Comment by oakcottage** [comment]
This is working now.  Thanks!
