### ISSUE TITLE
core_mosquitto not resolved in MQTT broker_url

### ISSUE THREAD

**Issue by tlpbu** [Poeschl/Hassio-Addons#173]
**Which addon?**
ICantBelieveItsNotValetudo (Home Assistant Supervisor Addon)

**Describe the bug**
MQTT address configures in `mqtt://<user>:<password>@core_mosquitto` form does not work as described in readme.
Exception:
```
Error: getaddrinfo ENOTFOUND core_mosquitto
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'core_mosquitto'
}
```

**To Reproduce**
Set `mqtt.broker_url` value in addon configuration to `mqtt://<user>:<password>@core_mosquitto` format.

**Expected behavior**
Resolve local MQTT broker without going via router thus creating unnecessary performance penalty.

**System**

* Supervisor version: supervisor-2021.01.7
* Host system version: Home Assistant OS 5.10

**Comment by Poeschl** [comment]
Have you replaced the `<user>` and `<password>` placeholder with your login credentials?

Unfortunately I couldn't reproduce your issue.

**Comment by tlpbu** [comment]
Yes, when I have configured:
```
mqtt:
...
  broker_url: 'mqtt://myuser:mypass@192.168.0.2:1883'
```
addon can successfully connect.
But after changing ip address and port to `core_mosquitto` and restarting addon it prints in log the exception from bug description.
Tried just now.

Maybe something messing up if Mosquito addon in config has 4 ports exposed instead of just explicitly specified 1883 in working `ip:port` seup?

**Comment by Poeschl** [comment]
Is the issue still happening? I researched a little about it, and the error indicates a DNS problem. With the latest supervisor the internal address of the addon is shown in the ui.

Does it work with that hostname?

**Comment by tlpbu** [comment]
Great hint about addon internal address.
Despite I have not explicitly configured or changes any thing it appeared that in my case internal addess was `core-mosquitto` (note dash instead for underscore).

Addon connects to MQTT fine now with `mqtt://<user>:<password>@core-mosquitto`.

**Comment by Poeschl** [comment]
Uhh, I just noticed that the docs of the addon also states the underscore which should be a dash. 😅
I will change that asap. 

Big thoughts and all goes down with a typo 🙈
