### ISSUE TITLE
Addons use a deprecated format

### ISSUE THREAD

**Issue by tomlut** [Poeschl/Hassio-Addons#177]
**Which addon?**

Mopidy, MPD, rsync local, pigpio

**Describe the bug**

The above addons need updating accordigng to the following warning in the supervisor log:

`WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only.`

**To Reproduce**
1. Go to Supervisor / System / Supervisor Logs
2. View the log
3. This happens if the addons are installed or not.

**Expected behavior**

Addons to use the new format.

**Screenshots**

**System**

* Supervisor version:  supervisor-2021.02.5
* Host system version:  Home Assistant 2021.2.2

**Comment by Poeschl** [comment]
Will be fixed when #176 is merged.
