### ISSUE TITLE
MPD error (failed to connect the stream: No such entity)

### ISSUE THREAD

**Issue by AdmiralStipe** [Poeschl/Hassio-Addons#179]
**Which addon?**
MPD

**Describe the bug**
All of a sudden MPD is unable to produce sound on a Raspberry Pi 4B (was playing fine for months now via audio jack, using attached custom mpd.conf). The player plays the media file, but no audio can be heard. There's an error in log file - "Failed to play on "Home Assistant Pulseaudio" (pulse): failed to connect the stream: No such entity". Also there is no possibility to select an audio interface in the plugin settings anymore - before there were two interfaces to select between (can not remember the description, but something related to jack audio output), not there is only Default and Dummy - none of which works when selected. I assume this is the main cause fo the problem, but can't understand, why the addon can not see the interfaces anymore. 

[log.txt](https://github.com/Poeschl/Hassio-Addons/files/5958531/log.txt)
![screen](https://user-images.githubusercontent.com/64564398/107517817-84b70300-6bae-11eb-913b-f904334d0d0d.jpg)
[mpd.conf.txt](https://github.com/Poeschl/Hassio-Addons/files/5958537/mpd.conf.txt)

It happened around the same time when updating HA to 2021.2.2 and Raspbian regular APT update (could only find update of lxpanel-pulseaudio from 0.3 to 0.4 in logs). 
I tried to revert to old version of MPD and old version of Hassio, but it doesnt help. Unfortuantely I'm unable to revert lxpanel-pulseaudio to 0.3 to check that also. 

**System**
Operating system
Raspbian GNU/Linux 10 (buster) on Raspberry PI 4B
Docker version
20.10.3

Supervisor version: supervisor-2021.02.6
Host system version: Home Assistant core-2021.2.2, running on Raspberry Pi 4B in Docker (Supervised install)

**Comment by Poeschl** [comment]
I checked with the version you named (on HassOS, since thats the system of my dev-Pi), and it works flawlessly.

Is your host able to play some sounds? Try with aplay to get something from it. It seems that the error lays within your pulse configuration.

**Comment by AdmiralStipe** [comment]
Yes, it plays sounds normally otherwise (locally), if I initiate it directly from Raspbian... I tried with "aplay /usr/share/sounds/alsa/Front_Center.wav" and it works flawlessly, it also plays any local media filea and that's what puzzles me...

Any hints (links?) on what can i try with Pulse settings? I'm a Linux noob and have no idea which config to change to try...

(btw, I tried installing mopidy server in the meantime and the server is running, but I'm also unable to hear anything, when playing a media file there).

**Comment by Poeschl** [comment]
I'm also happy myself when the pulseaudio config is working, so unfortunately no big knowledge here as well.

With `pacmd list-sinks | grep -e 'name:' -e 'index:'` all of your audio devices should be listed. Do you get any output?

**Comment by AdmiralStipe** [comment]
That returns
`   index: 0
	name: <alsa_output.platform-soc_audio.digital-stereo>
  * index: 1
	name: <alsa_output.platform-soc_audio.analog-stereo>
`
Which probably means HDMI and 3.5 jack output and that analog (jack) is selected as default... but other than that I have no idea...

**Comment by Poeschl** [comment]
Ok, so the host has everything in place. Can you execute the following docker command? It shows the pulseaudio config for the Home Assistant core.
` docker exec -it homeassistant cat /etc/asound.conf`

To see the pulseaudio config  of the MPD addon (which should be the same) type:

` docker exec -it addon_243ffc37_mpd cat /etc/asound.conf`

Is the output different?

**Comment by AdmiralStipe** [comment]
The both return the same: 
`
# Default to PulseAudio

pcm.!default {
    type pulse
    hint {
        show on
        description "Default ALSA Output (Home Assistant PulseAudio Sound Server)"
    }
}

ctl.!default {
    type pulse
}

`

**Comment by Poeschl** [comment]
Last idea from my side: Set the sink name in the custom config. `sink "default"`

Does it work without the custom config? I didn't saw a big change there.

**Comment by AdmiralStipe** [comment]
Unfortunately it doesn't work... same error. 
Yeah, config is nearly the same as default, jsut increased the buffer (last line).

**Comment by AdmiralStipe** [comment]
If this helps... in the menatime I managed to make mopidy play, but only if run in [terminal](https://docs.mopidy.com/en/latest/running/terminal/)... if I try to run it as a [service](https://docs.mopidy.com/en/latest/running/service/#service), it does not work... there seems to be the same config (at least what I could see) in both cases, but only terminal works (I tried it running as a user and as root, it works in both cases)... may be something related to this? 
I mean, with mopidy working, I found a solution, but I would rather use MPD instead of mopidy with another addon...

Is it possible to enable some kind of more detailed error log for MPD, to check, what goes on in background?

**Comment by Poeschl** [comment]
I included a verbose config flag in the addon which gives more debug output, just put `verbose: true` in the config and it should give you more details.

**Comment by AdmiralStipe** [comment]
Actually the log in my previous post has already been created with Verbose flag checked, but it doesn't tell much (well, at least not to me)...

**Comment by AdmiralStipe** [comment]
> Can you execute the following docker command? It shows the pulseaudio config for the Home Assistant core.
> ` docker exec -it homeassistant cat /etc/asound.conf`
> ` docker exec -it addon_243ffc37_mpd cat /etc/asound.conf`

Just to be sure... which asound.conf is that? The one in my Raspbian "etc/" folder or is there another one in docker? Cause I checked the one on Raspbian and it's content is completely different than this, what shows here...
In Raspbian I have a symlink in etc/asound.conf which redirects to /home/pi/.asoundrc
And this .asoundrc only has the following content: 

`
defaults.pcm.card 1
defaults.ctl.card 1
`

I really have no idea how this works, but may this be the issue? That the native Raspberry has different settings and therefore can play media, but HA and MPD can not?

**Comment by Poeschl** [comment]
@AdmiralStipe The both asound files I requested are the files from inside the homeassistant container and inside the addon container.

Somehow the supervisor should map the config inside the addon. If it is fixed to the etc config, this could be the issue indeed.

**Comment by AdmiralStipe** [comment]
OK, I'm googling on "how to edit files in docker container" right now for some testing, which may include crashing MPD/HA :).

**Comment by Poeschl** [comment]
@AdmiralStipe You can go inside the bash of the mpd container with docker exec -it addon_243ffc37_mpd bash this could give you a Kickstart. 😉

**Comment by Poeschl** [comment]
I also researched a little bit about how the audio is mapped into an addon.

It seems that `/etc/pulse/client.conf`, `/run/audio` and `/etc/asound.conf` of the host system gets mounted as read only in the host. And that it.

**Comment by AdmiralStipe** [comment]
Seems to me, that I have a completely different problem... when checking "ha audio log" i get a veeery long list of audio errors in HA, including:
"could not open configuration file /usr/share/alsa/ucm2/bcm2835 Headphones/bcm2835 Headphones.conf"
"UCM not available for card bcm2835 Headphones"
"Failed to find a working profile."
So most likely the problem lies there, not in your addon. 
If you have any hints on how to proceed with troubleshooting (although not related to you) I will gladly hear it, otherwise we can close this issue :).

**Comment by Poeschl** [comment]
Unfortunately I have no hints for you in mind. I hope you will find the issue. 😉
