### ISSUE TITLE
Unable to update Mopidy to 1.2.4

### ISSUE THREAD

**Issue by ShonP40** [Poeschl/Hassio-Addons#181]
**Which addon?**

Mopidy

**Describe the bug**

Trying to update from 1.2.3 to 1.2.4 results in an error

`ERROR (SyncWorker_1) [supervisor.docker.interface] Can't install ghcr.io/poeschl/ha-mopidy-armv7:1.2.4 -> 500 Server Error for http+docker://localhost/v1.40/images/create?tag=1.2.4&fromImage=ghcr.io%2Fpoeschl%2Fha-mopidy-armv7: Internal Server Error ("name unknown").`

**To Reproduce**

Click on Update on the addons page, the button will turn red and an error will be displayed in the Supervisor logs.

**Expected behavior**

I expected the Supervisor to download the latest version of the addon and install it

**Screenshots**

![image](https://user-images.githubusercontent.com/13995143/107664329-fb2e3080-6c94-11eb-949d-93bd5679b5e3.png)

**System**

* Supervisor version:  `supervisor-2021.02.6`
* Host system version:  `Home Assistant OS 5.11
`

**Comment by Poeschl** [comment]
Fixed with a8199c0656e4544c2ea3c62e593a20f4bbcae87c. The mopidy images build was disabled, the image will be available after the [build](https://github.com/Poeschl/Hassio-Addons/runs/1881620354) is done.

**Comment by Poeschl** [comment]
Reverted version for mopidy. For a build most of the addon needs to be modernized.
