### ISSUE TITLE
Syncthing: no files synced or found

### ISSUE THREAD

**Issue by marcianito** [Poeschl/Hassio-Addons#182]
Thanks for bringing syncthing, one of my favorite little programs, to HA!!

My problem is, that I cannot find any synced files on the HA system. I tried with different folders on the HA system (pi running Hass OS):

   /root/config/www/syncfolder
   /mnt/syncfolder
   /media/<ssd>/syncfolder

none of them worked.

I have no error within syncthing. The global and local states are identical but when looking for the files on the system I cannot find them.
Syncthing is run with user root I guess (I didn't change anything, just installed and started it). I get a warning within syncthing that it "should not be run as priviliged user". Anyway, if the case, it should have all the rights (so less problems!).

The only suspicious thing I could find is in the logs, which I don't understand. Maybe it helps to solve this problem.

 ``multicastBeacon@0x40000c0cd0/writer' (1.999968 failures of 2.000000), restarting: true, error: write udp [::]:41992->[ff12::8384]:21027: sendmsg: cannot assign requested address``

Where are you storing your synced data to later use in HA? (I want to sync pictures for display).
Thanks in advance and keep up all the good work!

**Comment by Poeschl** [comment]
To get to your files you need to use one of the mounted folders  `/share`, `/config`, `/backup`, `/addons` or `/ssl` to map the data out of the addon container.

Every other folder in the addon is only inside the addon and will be deleted on addon stop.

**Comment by marcianito** [comment]
Thanks for the quick reply!
So I thought I tried this with ``/root/config/www/syncfolder`` which also didn't work.
But do I understand correctly that within the syncthing screen, on folder location I just literately write e.g. ``/config/myfolder`` then?

**Comment by Poeschl** [comment]
On a HassOS installation there are the shared folders mentioned above which a addon can access.

The addon is a own system for itself, so when ssh'ing in HA you won't find any files of the addon. Only the shared folders can be accessed. 

When syncthing synces a folder located at `/share/sync`, the files there can be also seen by the ssh terminal (or also the samba addon) in the folder `/share/sync`.

**Comment by marcianito** [comment]
great! I needed this extra explanation! Now it works! Thank you! awesome!! :)
