### ISSUE TITLE
0.2.8 : Skipping map generation as it has not changed.

### ISSUE THREAD

**Issue by Kugelfang666** [Poeschl/Hassio-Addons#189]
**Which addon?**

ICanotbeliefeitsnotvaletudo
**Describe the bug**

the updated to 0.2.8 worked great and the syntax error is gone. however now the map does not get rendered and the log is flooded with `Skipping map generation as it has not changed.`

The custom map card of valetudo however correctly renders the map and using MQTT explorer is can see that the topic is updating 
<img width="911" alt="Bildschirmfoto 2021-02-19 um 11 00 46" src="https://user-images.githubusercontent.com/3289654/108489643-148d3900-72a2-11eb-889b-19b0a6b520d9.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**

* Supervisor version: 
* Host system version:

**Comment by Poeschl** [comment]
The Skipping map generation message is normal since ICantBelieveItsNotValetudo outputs this everytime it skips the rendering.

Does the mqtt image gets updated on your broker? For me its working fine since the update (still on an old valetudo version).

![2021-02-19 14_58_04-Übersicht - P-Assistant](https://user-images.githubusercontent.com/5469257/108513682-34812480-72c3-11eb-8f06-47f4cd9be1df.png)

**Comment by Kugelfang666** [comment]
Yes on the broker it's updating. That is why the custom map card renders correctly

**Comment by Poeschl** [comment]
How do you receive the addon image? The addon don't provide the map as image anymore.

**Comment by Kugelfang666** [comment]
https://github.com/TheLastProject/lovelace-valetudo-map-card

**Comment by Kugelfang666** [comment]
There is a custom Lovelace card that can be installed via HACKS,

The downside is the image is not available as a camera in HA. This I cannot push the images with a notification. Therefore your solution is much better

**Comment by Poeschl** [comment]
I know the card as well. Can you try removing the valetudo cam from your setup? After a restart of the addon it should come back and also announce itself via mqtt on `homeassistant/camera/<your-identifier>`.

If that's working the addon does work correctly and the issue is in the process of image getting on HA.

**Comment by Kugelfang666** [comment]
I honestly don’t get what’s going on, 

The MQTT topic from Valentudo is updated since the custom card renders the map and is updating with the robot driving.

You App starts, connects to the MQTT server and exposes the addition camera in homeassistant/camera/<your-identifier>.

Still in the log of your adding i only see the skipping generation message and i don’t get the image served in HA.... 

totally odd.... any idea on what i can try?

**Comment by Poeschl** [comment]
Nothing about it in HA log? Like mqtt failing? Does it get messages when listening via mqtt debug?

**Comment by Kugelfang666** [comment]
OK one step forward one step backward:

Forward: The topic of the map has changed. I installed your latest version and used the default configuration. However with Valetudo 2021_02 the map topic has changed from 

valetudo\rockrobo\map_data 

To

valetudo\robot\map_data

This was a clear mistake on my side...

The step backward: 
Now I‘m back to the syntax error..

![CED69788-55D3-4D33-991A-9258EBEA7379](https://user-images.githubusercontent.com/3289654/108526769-d27beb80-72d1-11eb-8a5e-27660006fcc8.jpeg)

**Comment by Poeschl** [comment]
Good work figuring out the topic change. I need to update the addon defaults as well.

This sounds very similar to https://github.com/Hypfer/ICantBelieveItsNotValetudo/issues/45 like we said in your last issue.

**Comment by tlpbu** [comment]
I am also have both problems mixed:
```
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at MqttClient.<anonymous> (/app/lib/MqttClient.js:133:43)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/app/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:410:12)
    at work (/app/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:307:11)
Skipping map generation as it has not changed.
Skipping map generation as it has not changed.
```
Not event clear why it attempts to parse json - `map_data` content start with �PNG

**Comment by Poeschl** [comment]
Lets go over to #187 since this issue is not about the syntax.

**Comment by Poeschl** [comment]
I just dig into the insides of ICantBelieveItsNotValetudo, and it expects the optional compressed and encoded data on  `valetudo/robot/map_data` and outputs the image on `valetudo/robot/map`.

At my setup with an Valetudo `0.6.1` its working fine. Can you confirm that with the latest valetudo on the robot @Kugelfang666 @tlpbu ?

**Comment by Hypfer** [comment]
The log flood should be gone in ICBINV 2021.3.1
