### ISSUE TITLE
Missing init command in all addons

### ISSUE THREAD

**Issue by jokerigno** [Poeschl/Hassio-Addons#203]
**Which addon?**
Valetudo Mapper

**Describe the bug**
It starts but then it stops

**To Reproduce**

1. Go to Start
2. Wait
3. After few seconds is it stopped.
4. See logs

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-config: executing... 
[18:05:06] INFO: Setup config
[cont-init.d] setup-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:05:06] INFO: Start valetudo-mapper
[cmd] /bin/ash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Expected behavior**
Addon stays on

**System**

Versione | core-2021.3.3
-- | --
Tipo di installazione | Home Assistant OS
Sviluppo | false
Supervisore | true
Docker | true
Ambiente virtuale | false
Versione Python | 3.8.7
Famiglia del Sistema Operativo | Linux
Versione del Sistema Operativo | 5.4.99
Architettura della CPU | x86_64
Fuso orario | Europe/Rome

**Comment by nortuzar** [comment]
Same thing here, running it on a virtual machine in windows 10
## System Health

version | core-2021.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64
timezone | America/Santiago

**Comment by phtg** [comment]
Same here, on a RPi4.

## System Health

version | core-2021.3.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.11.3
Stage | running
Available Repositories | 758
Installed Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 28.6 GB
disk_used | 10.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.12.5), Terminal & SSH (9.0.2), ESPHome (1.16.2), Mosquitto broker (5.1.1), File editor (5.2.0), Node-RED (8.1.3), Samba share (9.3.1), Bitwarden RS (0.8.0), Let's Encrypt (4.11.0), Log Viewer (0.9.1), MariaDB (2.2.2), Zigbee2mqtt (1.18.1-1), Samba Backup (4.4), Valetudo Mapper (1.8.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 10
views | 26
mode | storage

</details>

**Comment by Poeschl** [comment]
It seems that it also affects other addons as well. I will look at it as soon as possible (this might not be this week).

As workaround the addon folder can be copied from the repository to your `/addons` share and then remove the `image: .. ` line from the `config.json`. After a refresh on the addon store you should be able to install it as local addon. 😉

**Comment by blueshiftlabs** [comment]
FYI, this appears to be an issue with the container - it seems that it has the wrong CMD:

```
# docker container inspect d60c
[
    {
        "Id": "d60c4361313e0af199c4cd4b147b2277f3d2c95f243545c5f0ee1c0b7d4f60f2",
        "Created": "2021-03-17T07:00:26.35677867Z",
        "Path": "/init",
        "Args": [
            "/bin/ash",
            "-o",
            "pipefail",
            "-c",
            "#(nop) ",
            "LABEL io.hass.version=1.5.2"
        ],
```

Running the container manually with `docker run` and passing `/init` with no arguments as the command works as expected.

**Comment by fufar** [comment]
same problem on Home Assistant 2021.3.4 Debian GNU/Linux 10 (buster)

**Comment by LiJu09** [comment]
> As workaround the addon folder can be copied from the repository to your `/addons` share and then remove the `image: .. ` line from the `config.json`. After a refresh on the addon store you should be able to install it as local addon.

Probably not, unable to exec bashio

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd: applying... 
[fix-attrs.d] mpd: exited 0.
[fix-attrs.d] ympd: applying... 
[fix-attrs.d] ympd: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
exec: fatal: unable to exec bashio: No such file or directory
[cont-init.d] setup-folders: exited 127.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 4.19.127-v7l
arch | armv7l
timezone | Europe/Bratislava

<details><summary>Hass.io</summary>

host_os | HassOS 4.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.11
disk_total | 58.0 GB
disk_used | 21.8 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok

</details>

**Comment by Poeschl** [comment]
Seems that the base image does not include the `/init` command anymore. I will add it to all of the addons now.

**Comment by Poeschl** [comment]
The update for the addons is now available. If not refresh the supervisor store. 
It would be nice to react with a 👍 it the issue is fixed at your system. If not please comment below.

**Comment by LiJu09** [comment]
But when try install as local addon. Removed the `image: ..` line from the `config.json`
I get this error `exec: fatal: unable to exec bashio: No such file or directory`

**Comment by Poeschl** [comment]
> But when I to try install as local addon. Removed the `image: ..` line from the `config.json`
> I still get this error `exec: fatal: unable to exec bashio: No such file or directory`

During build time or runtime? Did you remove only the image line, or did you also change the `build.json`?

**Comment by LiJu09** [comment]
During runtime. Removed only image line, nothing more changed.

**Comment by Poeschl** [comment]
@LiJu09 I just put the addon folder from the master-zip file on my test pi and removed the image line. Builds fine on the Pi and starts without an error for me. If you still want to compile it on your Pi and want to provide more information, please open an new issue.

**Comment by blueshiftlabs** [comment]
The new version did the trick - thanks @Poeschl for the quick fix!

**Comment by LiJu09** [comment]
Removed and installed it localy third time and it works :thinking:

**Comment by jokerigno** [comment]
For me it works too. If it is ok for everybody I will close the issue. Thank you @Poeschl for your support :)

**Comment by Zeunas** [comment]
It worked for me too, thank you soo much @Poeschl however...same thing seems to happen when you use a custom config:

`[10:02:57] INFO: Use custom config
cp: can't stat '/share/mpd/mpd.conf': No such file or directory
[cont-init.d] setup-settings: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.`

Complete noob here but could it be related to a similar issue?

**Comment by Poeschl** [comment]
> It worked for me too, thank you soo much @Poeschl however...same thing seems to happen when you use a custom config:
> 
> `[10:04:02] INFO: Use custom config cp: can't stat '/share/mpd/mpd.conf': No such file or directory [cont-init.d] setup-settings: exited 1. [cont-finish.d] executing container finish scripts... [cont-finish.d] done. [s6-finish] waiting for services. [s6-finish] sending all processes the TERM signal..`
> 
> Complete noob here but could it be related to a similar issue?

This is a unrelated error. The addon can not find your custom config.

**Comment by Zeunas** [comment]
> > It worked for me too, thank you soo much @Poeschl however...same thing seems to happen when you use a custom config:
> > `[10:04:02] INFO: Use custom config cp: can't stat '/share/mpd/mpd.conf': No such file or directory [cont-init.d] setup-settings: exited 1. [cont-finish.d] executing container finish scripts... [cont-finish.d] done. [s6-finish] waiting for services. [s6-finish] sending all processes the TERM signal..`
> > Complete noob here but could it be related to a similar issue?
> 
> This is a unrelated error. The addon can not find your custom config.

Ok let me open a new issue.
