### ISSUE TITLE
MPD stuck on a loop and doesn't start

### ISSUE THREAD

**Issue by Zeunas** [Poeschl/Hassio-Addons#205]
**Which addon?**
MPD

**Describe the bug**
Was working fine yesterday, then from this morning it keeps restarting and when it gets to this point on the the MPD addon log "[s6-finish] sending all processes the TERM signal." the Supervisor restarts the whole process again and just goes round and round in the same loop, see extract from Supervisor log:

21-03-11 21:20:05 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 243ffc37_mpd!
21-03-11 21:20:05 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_243ffc37_mpd application
21-03-11 21:20:06 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/poeschl/ha-mpd-aarch64 with version 1.5.2

**To Reproduce**
N/A not sure how to reproduce as I don't know the source of the problem

**Expected behavior**
MPD addon on a restart loop

**Screenshots**
Full extract from MPD addon log:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd: applying... 
[fix-attrs.d] mpd: exited 0.
[fix-attrs.d] ympd: applying... 
[fix-attrs.d] ympd: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
[21:25:19] INFO: Setup Folders
[cont-init.d] setup-folders: exited 0.
[cont-init.d] setup-settings: executing... 
[21:25:19] INFO: Setup settings
[cont-init.d] setup-settings: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cmd] /bin/ash exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Extract from the Supervisor log which is in constant loop:

21-03-11 21:20:05 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 243ffc37_mpd!
21-03-11 21:20:05 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_243ffc37_mpd application
21-03-11 21:20:06 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/poeschl/ha-mpd-aarch64 with version 1.5.2

**System**

* Supervisor version: supervisor-2021.03.4
* Host system version: Home Assistant OS 5.12

**Comment by Poeschl** [comment]
This issue is like #203, it will be handled there as well
