### ISSUE TITLE
PIGPIO: [1762134600] [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by phcella** [Poeschl/Hassio-Addons#209]
**Which addon?**
PIGPIO

**Describe the bug**
When I tried to control the fan that I have using pigpio, I'm getting this error "[1762134600] [Errno 32] Broken pipe"
This stated after I updated the addon

**To Reproduce**
This happened when I try to turn on/off.

**Expected behavior**

**Screenshots**
![Captura de tela 2021-03-18 193924](https://user-images.githubusercontent.com/20034679/111706797-aba5cc00-8821-11eb-91a8-34dc8e42c773.jpg)

**System**

* PIGPIO Version: 1.2.1
* Supervisor version: 2021.03.6
* Host system version: Home Assistant OS 5.12

**Comment by Poeschl** [comment]
Are you controlling pigpio over the pipe files? Were does this error message come from?
Can you post the log of the addon?

**Comment by phcella** [comment]
Hello,
I even don't know what is this pipe files. This error came from when I try to turn on/off the gpio entity on the lovelance.
The screenshot I attached is form lovelance when I tried to turn on.

I guess the addon is working ok, the log is below:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:34:27] INFO: Started pigpio
```

**Comment by Poeschl** [comment]
😁 Can you check your configuration inside Home Assistant against the integration page? 

Since the addon logs don't output anything, its out of scope of this repository. I guess somewhere between the switch and the addon is something not right configured.

**Comment by phcella** [comment]
I've already checked my configuration. It is really strange, because I didn't change anything on my configuration for months. The addon and Hassio was working perfectly before this update. Is there anyway that I can downgrade the addon version for tests?

**Comment by Poeschl** [comment]
@phcella Via ssh and the cli there is an command to update a addon to a specific version. This is the way I currently know

**Comment by phcella** [comment]
Is there any tutorial how to do that? Or the commands?

**Comment by phcella** [comment]
I reallt don't know what happened, but I restarted Hassio and all worked perfectly!! Thanks for your time and support
