### ISSUE TITLE
MPD custom config option not working

### ISSUE THREAD

**Issue by Zeunas** [Poeschl/Hassio-Addons#210]
**Which addon?**
MPD

**Describe the bug**
Working fine with no custom config but if option selected it keeps rebooting every time Supervisor kills it (Watchdog ON). On the the MPD addon log "[s6-finish] sending all processes the TERM signal." the Supervisor restarts the whole process again and just goes round and round in the same loop. mpd.conf is in the folder and I have tried in two different HA and same issue happens.

**To Reproduce**
Add "custom_config: /share/mpd/mpd.conf" to configuration. 
Paste mpd.conf in the /share/mpd/mpd.conf as per instructions.

**Expected behavior**
MPD addon on a restart loop

**Screenshots**
Supervisor:
21-03-19 10:29:20 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with 243ffc37_mpd!
21-03-19 10:29:21 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_243ffc37_mpd application
21-03-19 10:29:23 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on ghcr.io/poeschl/ha-mpd-armv7 with version 1.5.3

MPD:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd: applying... 
[fix-attrs.d] mpd: exited 0.
[fix-attrs.d] ympd: applying... 
[fix-attrs.d] ympd: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
[10:29:58] INFO: Setup Folders
[cont-init.d] setup-folders: exited 0.
[cont-init.d] setup-settings: executing... 
[10:29:58] INFO: Setup settings
[10:30:00] INFO: Use custom config
cp: can't stat '/share/mpd/mpd.conf': No such file or directory
[cont-init.d] setup-settings: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

```
**System**
Supervisor version: supervisor-2021.03.4
Host system version: Home Assistant OS 5.12

**Comment by LiJu09** [comment]
MPD 1.5.3, for me custom config working properly, check if dont have hidden file extensions if you are on windows

**Comment by Zeunas** [comment]
Crap...I'm such a noob just noticed that the cont file was in txt format (ie. mpd.conf.txt)....so sorry for wasting your time....
