### ISSUE TITLE
[MPD] Version 1.5.4 not available on all architectures

### ISSUE THREAD

**Issue by Poeschl** [Poeschl/Hassio-Addons#214]
**Which addon?**
MPD

**Describe the bug**
The MPD addon is not available on `armv7`, `armhf`, `aarch64`.

The build has problems with the cross-compiling with the Home Assistant builder.

Will be fixed as soon as possible. 😉

**Comment by Zeunas** [comment]
Is that why I get this error? Will you make it available to the remaining architectures at all?

`21-03-25 14:20:36 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install ghcr.io/poeschl/ha-mpd-aarch64:1.5.4 -> 500 Server Error for http+docker://localhost/v1.40/images/create?tag=1.5.4&fromImage=ghcr.io%2Fpoeschl%2Fha-mpd-aarch64: Internal Server Error ("name unknown").`

**Comment by Poeschl** [comment]
That's exactly the error what gets cause by it.
I will make it available again for sure.

**Comment by Zeunas** [comment]
> That's exactly the error what gets cause by it.
> I will make it available again for sure.

You're a star! Thanks!
PS.: I'll send you another coffee shortly ;) Your work is great!
