### ISSUE TITLE
[MPD] Update Docs 

### ISSUE THREAD

**Issue by Poeschl** [Poeschl/Hassio-Addons#216]
Update the docs to the new config options.

**Comment by Zeunas** [comment]
New playlist/media folders in addon configuration seems to be overriding mpd.conf options, as I have a media folder set up in a samba server and data base is not pulling through from that folder anymore. It may be covered in your new config options but just wanted to give you a heads-up.

**Comment by Poeschl** [comment]
@Zeunas
Can you write that in a new issue?
This shouldn't be the case. If a custom config is used, no modifications should be done on it.

**Comment by Zeunas** [comment]
Will do, let me get the details

**Comment by LiJu09** [comment]
Updated docs in #218
