### ISSUE TITLE
[MPD] mpd.conf folder options being overruled by the addon configuration

### ISSUE THREAD

**Issue by Zeunas** [Poeschl/Hassio-Addons#217]
**Which addon?**
MPD

**Describe the bug**
New media_folder and playlist_folder options under addon configuration is overruling the folder configuration set up under mpd.conf. 
Under addon configuration custom_config, media_folder and playlist_folder can be changed and MPD will read those (as per log) but which ever folder you set up under mpd.conf will be ignored.
I have a media folder set up under a samba share which I have added to the mpd.conf by replacing the default folder to "smb://user:password@ip/folder path" - this was working on MPD version 1.5.3 but not on the new version. I have also tried to copy this samba share folder under media_folder on the addon configuration but after saving it the addon defaults to the previous folder.
Deleting the options for media and playlist folder from YAML also doesn't work, as after saving the changes the addon defaults to previous options.

**To Reproduce**
1. Go to addon configuration and set up the folders or delete the options of media and playlist folder
2. Click on Save
3. And see if addon defaults to previous options

**Expected behavior**
I'd expect that whatever I put under the mpd.conf is not overruled by whichever folders are set up under media_folder / playlist_folder on addon configuration

**Screenshots**

Log from addon showing it's pulling through the correct folder paths set up under addon configuration - Which may also give a hint to why mpd.conf is being overruled.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] mpd: applying... 
[fix-attrs.d] mpd: exited 0.
[fix-attrs.d] ympd: applying... 
[fix-attrs.d] ympd: exited 1.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] setup-folders: executing... 
[09:14:03] INFO: Setup Folders
[cont-init.d] setup-folders: exited 0.
[cont-init.d] setup-settings: executing... 
[09:14:04] INFO: Setup settings
[09:14:05] INFO: Use custom config
[09:14:05] INFO: Set music folder
[09:14:05] INFO: Set playlist folder
[cont-init.d] setup-settings: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[09:14:06] INFO: Start MPD
[09:14:06] INFO: Start ympd
MPD Connecting to 127.0.0.1:6600
MPD connected.
`
**System**
* Supervisor version: supervisor-2021.03.6
* Host system version: Home Assistant OS 5.12

**Comment by LiJu09** [comment]
#218 shoud fix it

**Comment by Zeunas** [comment]
Super! I'll wait for the new version then
