### ISSUE TITLE
Error with special char in the password

### ISSUE THREAD

**Issue by patrice-guillemette** [Poeschl/Hassio-Addons#219]
**Which addon?**
Home Assistant Git Exporter

**Describe the bug**
My password contains the char @ as the last char and it doesn't work in the plugin.

**System**

* Supervisor version:  supervisor-2021.03.6
* Host system version: Ubuntu 18.04.5 LTS  Hass core-2021.3.4

**Comment by Poeschl** [comment]
What exactly doesn't work? Does the detection of the password not work?

**Comment by patrice-guillemette** [comment]
it can't push because the @ char is reserved to indicate the end of the password, kind of. The only way to make it work is to replace the @ by %40 in the password string. I dit it in the config so it's working great now but it could be nice to search and replace it in the password string.  Http authentication use this syntax :   user:password@domain but as my password contain the char @, the http authentication think that the domain is @github.com instead of githum.com. 

Got it working by setting my password as 
password = mysupersecretpassword%40
instead of 
password = mysupersecretpassword@

**Comment by Poeschl** [comment]
Got it 👍
