### ISSUE TITLE
How to install on Home Assistant Docker

### ISSUE THREAD

**Issue by oywino** [Poeschl/Hassio-Addons#225]
**Which addon?**

vnc-viewer
**Is your feature request related to a problem? Please describe.**

Installation failed because I'm not running Hass.io
**Describe the solution you'd like**

Ability to connect to HA using any VNC client
**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
The vnc addon uses noVnc internally to connect to a vnc server.
It is also possible to install it an a HA docker installation with following the regular installation of https://github.com/novnc/novnc.

**Comment by oywino** [comment]
Sorry, I don't understand.
What I want to do, is to connect to HA (Lovelace) using Apache Guacamole VNC

**Comment by Poeschl** [comment]
The addon allows to view the vnc interface of an other device. It does not serve the HA interface. 

Lovelace is only served via http.

**Comment by oywino** [comment]
Do you mean that it allows the VNC-UI of "another device" to be viewed/integrated in a Lovelace dashboard as a "card" ?

**Comment by Poeschl** [comment]
It integrates the "another device" as an additional section in the sidepanel like the logbook, not in a Lovelace card.

**Comment by oywino** [comment]
Ok, thanks.

**Comment by b2az** [comment]
Hi Markus (@Poeschl ),

I just wanted to use this issue to thank you for this Addon. 
We're using it on a daily basis and love it!
