### ISSUE TITLE
Supervisor local addons

### ISSUE THREAD

**Issue by avocadio** [Poeschl/Hassio-Addons#241]
**Which addon?**
git-exporter

**Is your feature request related to a problem? Please describe.**
Local hassio addons can be developed and maintained at the following location:
/root/addons/ or /mnt/data/supervisor/addons/local.
Reference: https://developers.home-assistant.io/docs/add-ons/tutorial

**Describe the solution you'd like**
Backing up the folder, it is currently conflicting with 'addons' should it be named 'local-supervisor-addons' ?

**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
Can I some more context? I don't get the point 😅
