### ISSUE TITLE
"No map data" after updating from 3.3.1 to 3.4.0

### ISSUE THREAD

**Issue by Sleepy89** [Poeschl/Hassio-Addons#252]
**Which addon?**
ICantBelieveItsNotValetudo

**Describe the bug**
After the automatic update from 3.3.1 to 3.4.0, the map was no longer displayed. There are no errors in the logs. I did not change the firmware of the vacuum cleaner.

**To Reproduce**
1. Install plugin 3.3.1
2. Change the default mqtt settings in the vacuum cleaner "valetudo / valetudo / MapData / map-data"
3. Configure the plug-in according to the changes in the vacuum cleaner.
4. Make sure. that the map is displayed.
5. Automatically update the plugin
6. The map will disappear in the web interface and in "camera.valetudo_rendered_map"

**Expected behavior**
I want my map back!

**Screenshots**
![image](https://user-images.githubusercontent.com/17094753/123224279-5c370200-d4da-11eb-86b4-e73e1a4726eb.png)

**System**
* Supervisor version: supervisor-2021.06.3
* 
* Host system version: core-2021.5.1

## System Health
version | core-2021.5.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.11-v7l+
arch | armv7l
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4978
Installed Version | 1.12.4
Stage | running
Available Repositories | 848
Installed Repositories | 1

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.3
docker_version | 20.10.2
disk_total | 28.2 GB
disk_used | 10.9 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Mosquitto broker (6.0.1), Zigbee2mqtt (1.18.1-1), MariaDB (2.2.1), Nginx Proxy Manager (0.11.0), Home Assistant Google Drive Backup (0.104.3), Terminal & SSH (9.1.3), ICantBelieveItsNotValetudo (3.4.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
error | /config/ui-lovelace.yaml not found
views | 3
mode | storage

</details>

**Comment by Poeschl** [comment]
@Sleepy89 Can you provide the logs of the addon?

**Comment by Poeschl** [comment]
It tested your case today and couldn't reproduce the missing image. Can you try to restart your MQTT broker? Does the image show up when pressing the "Open Webinterface" button on the addon details page?

**Comment by Sleepy89** [comment]
> Он проверил ваш случай сегодня и не смог воспроизвести недостающее изображение. Можете ли вы попробовать перезапустить своего брокера MQTT? Отображается ли изображение при нажатии кнопки «Открыть веб-интерфейс» на странице сведений о надстройке?

The electricity was cut off today, which led to a reboot of the raspberry. After that, the card appeared. Sorry for the wasted time!
p.s. At the time of the problem, in the plugin logs, I did not notice any error or warning messages or messages that were not logically terminated. But I did not save the logs themselves.

**Comment by Poeschl** [comment]
All good 😉 I needed to upgrade my system anyway 😁
