### ISSUE TITLE
Pigpio not found

### ISSUE THREAD

**Issue by jalicz** [Poeschl/Hassio-Addons#253]
**Which addon?**
pigpio

**Describe the bug**
addon not found

**To Reproduce**
1. click INSTALL ON MY
2. Open link - OK
3. Opening Supervisot page - addon not found
4. Reload addons in store - without difference

**Expected behavior**

**Screenshots**

**System**
core-2021.6.6
supervisor-2021.06.6
Home Assistant 2021.6.6
Home Assistant OS 6.1
Docker 20.10.6
frontend: 20210603.0 - latest
Python : 3.8.9
board : rpi4-64
not beta

**Comment by Poeschl** [comment]
As the images on the [README](https://github.com/Poeschl/Hassio-Addons/tree/master/pigpio) states: The pigpio add-on is not available for the aarch64 architecture, which the Pi4 has.

**Comment by Poeschl** [comment]
Hmm, I maybe you also need to add the repository also before that. But I'm not sure about it

**Comment by jalicz** [comment]
> 
> 
> As the images on the [README](https://github.com/Poeschl/Hassio-Addons/tree/master/pigpio) states: The pigpio add-on is not available for the aarch64 architecture, which the Pi4 has.

**Comment by jalicz** [comment]
> 
> 
> Hmm, I maybe you also need to add the repository also before that. But I'm not sure about it

OK, how do I add repository ?

**Comment by Poeschl** [comment]
@jalicz See the how to here: https://github.com/Poeschl/Hassio-Addons#installation

**Comment by jalicz** [comment]
> 
> 
> As the images on the [README](https://github.com/Poeschl/Hassio-Addons/tree/master/pigpio) states: The pigpio add-on is not available for the aarch64 architecture, which the Pi4 has.

So what is the supplement when GPIO is only on the RPI board?

**Comment by Poeschl** [comment]
As far as I know the gpio can get input and switch the pins on or off with just HA installed (https://www.home-assistant.io/integrations/rpi_gpio/)

To control PWM values the pigpio needs to be used. 😉
Maybe there is a version to target arm64 devices. If so I will gladly include it.

**Comment by jalicz** [comment]
I'm using my pins input - output On RPI. Now I need to use PWM, according to the https://github.com/soldag/python-pwmled#installation Manual, this is not the HA OS

**Comment by jalicz** [comment]
> 
> 
> @jalicz See the how to here: https://github.com/Poeschl/Hassio-Addons#installation

I added repository, but no new items didn't meet me, I tried restart, but no difference.

**Comment by Poeschl** [comment]
Then you are right and you will need to install pigpio inside the homeassistant container or use the addon.

I will look if the addon could also be build for the Pi4. For the progress of it see #254

**Comment by jalicz** [comment]
> 
> 
> > @jalicz See the how to here: https://github.com/Poeschl/Hassio-Addons#installation
> 
> I added repository, but no new items didn't meet me, I tried restart, but no difference.

reload browser - OK

**Comment by jalicz** [comment]
instal on RPI4 - OK
PWM light entity added
i'll test the pin output later
