### ISSUE TITLE
Ingress support?

### ISSUE THREAD

**Issue by nickrout** [Poeschl/Hassio-Addons#256]
**Which addon?**

Owasp zap
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Not sure if this is a bug or a feature request. Is there ingress support in this (and I missed it)? Or is it envisaged in the future?
**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
I would love to have ingress support for it. Right now it's not enabled since the used web framework of ZAP didn't support relative links.
