### ISSUE TITLE
MPD / Can't find media_duration attribute

### ISSUE THREAD

**Issue by TheUadzhet** [Poeschl/Hassio-Addons#257]
More in this topic https://github.com/KoljaWindeler/ytube_music_player/issues/108

Is there any chance to enable this media_duration attribute?

**Comment by Poeschl** [comment]
All attributes of the mpd integration are coming from the build-in integration of Home Assistant.
The addon just provides just an player which can be controlled via http requests. Home Assistant Core is controlling it and takes care about the right metadata.
