### ISSUE TITLE
Speed up OWASP ZAP startup

### ISSUE THREAD

**Issue by psiinon** [Poeschl/Hassio-Addons#259]
What features do you think are key for using ZAP in this environment?
If you let me know then we should be able to recommend which ZAP add-ons you _dont_ need to include.
Removing add-ons will help ZAP start faster.

**Comment by Poeschl** [comment]
That's a good idea. 👍
I mostly use ZAP in the addon to do MITM sniffing.
It would be nice to have the opportunity to include/exclude add-ons dynamically on start. Then a option for the addon could be provide a granular control.

**Comment by psiinon** [comment]
ZAP already supports the option to install add-ons from the command line "-addoninstall <name>" as per https://www.zaproxy.org/docs/desktop/cmdline/ (and uninstall them for that matter)
We actually provide a 'bare' docker image https://hub.docker.com/r/owasp/zap2docker-bare/ for people who want a minimal install.
If you fancy playing around with this then one option would be to try removing all of the add-ons from the plugins directory just to see how much faster ZAP loads - if it doesnt make much difference then maybe this isnt worth spending too much time on :)

**Comment by Poeschl** [comment]
I will look into it 👍 and report back.

**Comment by Poeschl** [comment]
Tested this evening a little with/-out the add-ons. On emulated ARM the startup without all addons saves around 30s. This is worth to look at. Maybe not urgent, but it is on my list now.

Do the command line switches also work with the zap-webswing launch script, or do I need to set the `ZAP_WEBSWING_OPTS` variable?

**Comment by psiinon** [comment]
You will need to set `ZAP_WEBSWING_OPTS` as per https://www.zaproxy.org/docs/docker/webswing/

**Comment by Poeschl** [comment]
Since the ZAP addon is discontinued, this will also be closed
