### ISSUE TITLE
Make it easier to understand the size implications

### ISSUE THREAD

**Issue by kappuchino** [Poeschl/Hassio-Addons#260]
My backups grew quite large since I did not understand the hassio config backup rules/strategy first.
In order to help lesser experienced users, I would suggest to clarify the description of the addon to

[...]
Folders available

When using this addon to permanently hold your data, put the synced folder inside /data. Otherwise it will be deleted on container restart. Note that this folder and its contents will be included in each backup of the addon.

Also the /share, /confg, /backup, /addons and /ssl folders are mapped inside.  You can use them as persistant storage.  Some of those are not included in backups of the hassio configuration by default.

Syncing those folders can also be used to backup the Home Assistant backups, for example. 😉
[...]

And: Thank you for providing a syncthing container to hassio!

**Comment by Poeschl** [comment]
That's a good idea.
I never ran into it, since using syncthing to backup the backups 😅

**Comment by kappuchino** [comment]
(Context: I use hassio on a rpi4 with 8gb and the Argon ONE M.2 case with a 1TB ssd blade. With this I have plenty of space and thanks to your provided addon I can mirror all my syncthing folders from the regular systems one way to the raspi as a backup in case of loss of my laptop, mobile, etc.)

**Comment by Poeschl** [comment]
Uh, that's neat.
