### ISSUE TITLE
Unable to find service media_player/play_media

### ISSUE THREAD

**Issue by emacsLover** [Poeschl/Hassio-Addons#27]
Hi

Thank you for your addons.

I've installed your picotts_remote and the mopidy addon as well.

1. http://raspi:8123/developer-tools/service
2. select tts/picotts_remote_say
3. message: 'bla'
4. send

`Failed to call service tts/picotts_remote_say. Unable to find service media_player/play_media`

I've read through the mopidy readme though can't see what part I missed

Running hass.io on raspi pi

**Comment by Poeschl** [comment]
Can you give me more information?
I tried replicate your scenario with following settings:

1. Installed PicoTTS Plugin Version 1.0-3
2. Installed Remote PicoTTS Component (copied the folder to config folder)
3. Installed Mopidy (P-Version) Version 1.1.0 with following config
![image](https://user-images.githubusercontent.com/5469257/67659973-f3dafa80-f95d-11e9-8d91-f96ba67591c9.png)
4. Add picoTTS to config
```yaml
- platform: picotts_remote
    host: localhost
    port: 59126
```
5. Restart
6. Executed:
![image](https://user-images.githubusercontent.com/5469257/67659885-c8f0a680-f95d-11e9-8ce2-8c22c53d0516.png)

After executing I'm hearing "blabla" through the connected speakers.

**Comment by emacsLover** [comment]
> Installed PicoTTS Plugin Version 1.0-3

Can you please eloborate a bit? How would I install that (alongside mopidy and picotts_remote).
