### ISSUE TITLE
Run more than one instance?

### ISSUE THREAD

**Issue by jds11111** [Poeschl/Hassio-Addons#271]
**Which addon?**
I Can't Believe Its Not Valetudo

**Is your feature request related to a problem? Please describe.**
No, it works great

**Describe the solution you'd like**
Be able to run the instance a second time, for another robot

**Describe alternatives you've considered**
Run it on another machine, not as an addon.

**Additional context**
ICBINV works for only one robot, but if another instance is run, a different port can be used for a second robot.
I have no idea how easy/difficult it would be to implement here as an addon, so just mentioning.

**Comment by Poeschl** [comment]
Running 2 instances of ICBINV can be done like described in #62.

For multiple instances inside a addon it might need some more work, especially for the several individual configs. I guess at least 2 instances is suitable for now. 

That said, I'm also happy to retrieve a PR for a "MULTI-ICBINV" 😁

**Comment by jds11111** [comment]
Thanks for the response.  You are right that running 2 instances of ICBINV is the way to go, since the original works that way. However, I don't understand enough how HA runs docker containers to implement that. Is that just the "Local Build" instructions at the bottom of the "Local Add-On instructions" that you linked to in issue 62? I.e., copy the contents of your ICBINV into `/addons`, and run something like `docker run --rm -ti --name hassio-builder --privileged \
  -v /path/to/addon:/data \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  homeassistant/amd64-builder -t /data --all --test \
  -i my-test-addon-{arch} -d local`

**Comment by Poeschl** [comment]
When the addon is copied in the addon folder. It is shown on the Supervisor UI as local addon.

You don't need to interact with docker or command line at all.

**Comment by jds11111** [comment]
Thanks---that worked. I had to remember to flush the cache of the browser to see it. You can use the configuration of the original to make a webserver:
```
webserver:
  enabled: true
  port: 3001
```
which can then be reached by a browser in the network.  Now I am just trying to figure out how to get these png files to show up in telegram notifications.

**Comment by Poeschl** [comment]
The Webserver is enabled by default 😉
This is fixed.
