### ISSUE TITLE
[Home Assistant Git Exporter] Make branch configurable

### ISSUE THREAD

**Issue by notorious-gay** [Poeschl/Hassio-Addons#272]
**Which addon?**
Home Assistant Git Exporter

**Is your feature request related to a problem? Please describe.**
Many developers are switching from master being the default to main due to the connotations of main being more neutral than the former.

See https://github.com/github/renaming - https://sfconservancy.org/news/2020/jun/23/gitbranchname/

Unfortunately it appears that the master branch is hard coded at the following points:

https://github.com/Poeschl/Hassio-Addons/blob/91e740ad27e140e1450eea1acbce8ef18a52d3f8/git-exporter/root/run.sh#L48
https://github.com/Poeschl/Hassio-Addons/blob/91e740ad27e140e1450eea1acbce8ef18a52d3f8/git-exporter/root/run.sh#L190

This prevents the add-on from working with repositories that do not use the legacy naming scheme 😢 

**Describe the solution you'd like**
It would be awesome if we could configure the branch name under repository.branch. (I'm happy to produce a PR if the issue is accepted 👌🏻)

**Describe alternatives you've considered**
Renaming to master or running both branches side by side would allow the add-on to function but this would be a messy workaround IMO.

**Additional context**
None to add.

**Comment by Poeschl** [comment]
I would go for a configurable branch name where the addon is pushing and pulling. 😉

Like you suggested a setting could specify the branch. The default for it should be `main` then.

A PR is more than welcome.

**Comment by Poeschl** [comment]
@notorious-gay How is it going? I see you made already a branch ;)
