### ISSUE TITLE
Syncthing: "add-on component not found"

### ISSUE THREAD

**Issue by Vinz87** [Poeschl/Hassio-Addons#273]
**Which addon?**
Syncthing

**Describe the bug**
Clicking on "Install on my Home Assistant" button I get a "Add-on component not found" error.

**System**

* Supervisor version: supervisor-2021.09.6
* Host system version: Home Assistant OS 6.4

**Comment by Poeschl** [comment]
Before using the button for a fast installation the repository needs to be added inside the supervisor.
See https://github.com/Poeschl/Hassio-Addons#installation

**Comment by Vinz87** [comment]
Got it, thank you
