### ISSUE TITLE
cant get rsync to work, permission denied (13)

### ISSUE THREAD

**Issue by philipp089** [Poeschl/Hassio-Addons#275]
**Which addon?**
rsync

**Describe the bug**
get permission denied but user is allowed to write at that folder, at least i am not sure what i missed. Maybe you can have a look and tell me in 5 seconds what i am doing wrong. I tried almost everything i know about.  I do not know what **"error in file IO (code 11) at main.c(682)"** should tell me. 

**To Reproduce**
start the addon and look at the logs in my case

**Expected behavior**
creating of config-folder and syncing

**Screenshots**

<img width="801" alt="rsync_log" src="https://user-images.githubusercontent.com/66092908/137595251-c2962b86-b906-4b00-8045-3ab691f5552a.png">
<img width="790" alt="rsync_options" src="https://user-images.githubusercontent.com/66092908/137595253-e0e20516-d64e-4b1c-9588-815c25d9796e.png">
<img width="518" alt="omv_user_permissions" src="https://user-images.githubusercontent.com/66092908/137595257-67790a29-61e4-46f3-999f-3e0ae184a8d3.png">
<img width="436" alt="user_priviliges" src="https://user-images.githubusercontent.com/66092908/137595260-9aeba763-7531-47e2-8f3d-e932e9f2a62c.png">
<img width="465" alt="omv_user_home_folder" src="https://user-images.githubusercontent.com/66092908/137595256-b8edb86b-e407-476d-91d3-510252d58d03.png">

**System**

* Supervisor version: supervisor-2021.10.0
* Host system version: Home Assistant OS 6.5
* Core version: core-2021.10.4

**Comment by Poeschl** [comment]
So when logging in with the user credentials via ssh the user `Philipp` can create a new folder under `/home/Philipp` like `/home/Philipp/config` ?

Unfortunately no 5 seconds tipp to fix it.
