### ISSUE TITLE
MPD not playing http://.../xx.mp3

### ISSUE THREAD

**Issue by jTd7bPLFb** [Poeschl/Hassio-Addons#277]
I am trying to get mpd play the m3u files - 
each file has one audio stream in it
for example
http://ic.streann.com/rockandpop

It works fine with my satellite mpd instances on raspberries, but not directly in home assistant plugin.
(local mp3 files are played without issues)

Any idea?

**Comment by Poeschl** [comment]
I assume that the playlist files are in the playlist folder. Right?

Unfortunately no idea. Sry

**Comment by jTd7bPLFb** [comment]
Ok, I am closing this issue, as it was the usual 'problem between chair and keyboard' :)
Somehow the streaming did not work over LTE hotspot. Now, with cable connection, it magically works.
cheers
