### ISSUE TITLE
Latest version of Valetudo handles maps differently, so add-on needs updating

### ISSUE THREAD

**Issue by jds11111** [Poeschl/Hassio-Addons#284]
**Which addon?**
ICBINV

**Describe the bug**
Maps are now handled differently with version 2021.12.0 of Valetudo. ICBINV has been updated, so this addon probably needs to be updated as well.

**To Reproduce**
try looking at the map on the current version

**Expected behavior**
see a map

**Screenshots**

**System**
* Supervisor version: supervisor-2021.10.8
* Host system version: Home Assistant OS 6.6

**Comment by Poeschl** [comment]
Thanks for the hint, will look into upgrading the next days.
