### ISSUE TITLE
icantbelieveitsnotvaletudo crop options

### ISSUE THREAD

**Issue by ishioni** [Poeschl/Hassio-Addons#286]
**Which addon?**

icantbelieveitsnotvaletudo
**Describe the bug**

Options for map cropping are ignored. It got added around 2021.11, described [in the docs](https://github.com/Hypfer/ICantBelieveItsNotValetudo)
**To Reproduce**

1. Add an option like
```
mapSettings:
  crop_top: 400
```
2. Inspect config.json inside the container, the options is missing

**Expected behavior**

The map is cropped

**Screenshots**

**System**

* Supervisor version: 2021.10.8
* Host system version: HASSIO 6.6

**Comment by Poeschl** [comment]
Seems that I missed out the new settings ;) Fix should be there after an hour when the MR is merged.

**Comment by ishioni** [comment]
Thanks for the quick update!
