### ISSUE TITLE
Syncthing runs as privileged or system user?

### ISSUE THREAD

**Issue by FollowTheWizard** [Poeschl/Hassio-Addons#296]
Hi
I installed the add-on today and got greeted by this message "Notice: Syncthing should not run as a privileged or system user. Please consider using a normal user account."

Is this intended or did i configure?(not much to do) the add-on incorrectly?

Thanks & BR

**Comment by Poeschl** [comment]
Synching is running as root inside of the addon. This is nothing you can configure from the outside. 😉

Maybe I will switch the user internally, but right now this message can be ignored.

**Comment by salim-b** [comment]
> Maybe I will switch the user internally, but right now this message can be ignored.

@Poeschl It would be really nice if you could do that so the message wouldn't confuse new users (or existing ones with bad memory😅) anymore.

**Comment by salim-b** [comment]
Addendum: Note that additional steps must be taken in order for [ownership](https://docs.syncthing.net/advanced/folder-sync-ownership#elevated-permissions) and [extended file attribute](https://docs.syncthing.net/advanced/folder-sync-xattrs#elevated-permissions) synchronisation to work when not running as root (these features were introduced with Syncthing 1.21 and 1.22 respectively). It doesn't seem to be too complicated, only a matter of three additional shell commands (to be added to the Dockerfile, I guess):

```sh
chown root /usr/bin/syncthing
chmod 755 /usr/bin/syncthing
setcap CAP_CHOWN,CAP_FOWNER=pe /usr/bin/syncthing
```

**Comment by MuellerNicolas** [comment]
Hello, i've just installed the Syncthing-Addon and also stumble across this issue.
I found [this comment](https://forum.syncthing.net/t/the-meaning-of-syncthing-should-not-run-as-a-privileged-or-system-user-please-consider-using-a-normal-user-account/10034/2) related to this issue, stating that: `2. Any files created by Syncthing will be owned by root.`

I'm not yet familiar with the software, but i am wondering, if this could be a problem? Maybe you, @Poeschl, already considered it and it's not a problem :)

Thank you for the creation of this addon 👍
