### ISSUE TITLE
Crop and rotate

### ISSUE THREAD

**Issue by darkkatarsis** [Poeschl/Hassio-Addons#30]
**Which addon?**
ICantBelieveItsNotValetudo0.2.0

**Is your feature request related to a problem? Please describe.**
It would be great to have possibility to customize even more generated map.

**Describe the solution you'd like**
https://github.com/Hypfer/ICantBelieveItsNotValetudo/commit/0884f7c141551bc5c2d259b230f415107aeebf85

**Comment by Poeschl** [comment]
The latest version of the addon should have this functionality, but the default config was not changed.
I guess it would work, if you add the new config settings to the right section on in the addon config. 

Will cross-check it tonight

**Comment by Poeschl** [comment]
Fixed with 9caa7c0

Please close the issue if its working also for you.

**Comment by darkkatarsis** [comment]
I confirm image crop works fine. For rotation we have to wait, but I saw that work is underway. Thank you!
