### ISSUE TITLE
git-exporter:  SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by Wolvverine** [Poeschl/Hassio-Addons#305]
git exporter
 fatal: unable to access 'https://xxx.xxx.xxx.xxx/HomeAssistant_Config.git': SSL certificate problem: self signed certificate
Problem when repository server have self signed certificate

Need an option to disable certificate checking.

**Comment by Poeschl** [comment]
Will look into it, but first: This is not a bug, and there are issue templates. They should be used.

**Comment by Wolvverine** [comment]
Hello.
@Poeschl 
Is there any nailed down date when it will be possible to use a local repository with self-signed?

**Comment by Poeschl** [comment]
It will be done when its done. Busy in RL and no Prio for me. Feel free to contribute.

**Comment by Wolvverine** [comment]
@Poeschl 
You have in the pull request.

**Comment by Poeschl** [comment]
MR merged
