### ISSUE TITLE
Invalid addon repository for Mopidy

### ISSUE THREAD

**Issue by carryonrewardless** [Poeschl/Hassio-Addons#309]
When I add a new repository to my Supervised HA 2022.3.4 using

https://github.com/Poeschl/Hassio-Addons/mopidy

I get Invalid Add-on repository.
Am I doing something wrong or is something broken atm?

Thanks

**Comment by Poeschl** [comment]
You need to add `https://github.com/Poeschl/Hassio-Addons` as repository, this should work.

**Comment by carryonrewardless** [comment]
Thanks.
