### ISSUE TITLE
Unable to update MPD from 1.7.0 to 1.7.1

### ISSUE THREAD

**Issue by AdmiralStipe** [Poeschl/Hassio-Addons#311]
**Which addon?**

MPD
**Describe the bug**

When trying to update from 1.7.0 to 1.7.1 I get an error: 
Can't install ghcr.io/poeschl/ha-mpd-armv7:1.7.1: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=1.7.1&fromImage=ghcr.io%2Fpoeschl%2Fha-mpd-armv7&platform=linux%2Farm%2Fv7: Internal Server Error ("manifest unknown")

**To Reproduce**
Update from 1.7.0 to 1.7.1
**Expected behavior**

**Screenshots**

**System**

* Supervisor version: 2022.03.5
* Host system version: 2022.4.1

**Comment by Poeschl** [comment]
@AdmiralStipe Update coming soon. 😉 Working on it

**Comment by Poeschl** [comment]
MPD should be available now. All other addons as well when https://github.com/Poeschl/Hassio-Addons/actions/runs/2146765578 has finished.
