### ISSUE TITLE
git-exporter: add extra secrets patterns and _allowed_ secrets patterns

### ISSUE THREAD

**Issue by bjeanes** [Poeschl/Hassio-Addons#314]
**Which addon?**

git exporter

**Is your feature request related to a problem? Please describe.**

I have a lot of little Mijia BLE humidity/temperature sensors around the house. The MAC addresses get triggered as secrets when they aren't sensitive (to me). I'd like to be able to allow them.

On the other hand, it does _not_ detect the `bind_key: <secret>` for those sensors, which _should_ be a secret.

**Describe the solution you'd like**

Ideally, the add-on would have two options, both lists of strings, that would be iterated when secret patterns are configured in Git by the add-on

**Describe alternatives you've considered**

I can't think of an alternative for adding extra secrets based on how the add-on works (to the extent I can understand `run.sh`). I think I could turn off secret checking, commit the ones I wish to preserve, then turn it back on and it _might_ skip future checks. I am not 100% sure this is how `git secrets` works, but it is a workaround I am considering.

**Additional context**

n/a

**Comment by bjeanes** [comment]
Another example for allowing a secret is to allow something like a local/non-sensitive subnet (e.g. `172.16.0.0/12`, which in this case is just to allow other Docker containers to act as proxies)

**Comment by Poeschl** [comment]
MR merged
