### ISSUE TITLE
Scheduling

### ISSUE THREAD

**Issue by diginfo** [Poeschl/Hassio-Addons#318]
Firstly, thanks for taking the time to develop this.

I have rsync working, but can't seem to find how to run it on a schedule, ie daily.

I have looked through the documentation & readme but just cant see to find anything related to this ?

It does execute successfully, when I start the service, but it appears only to be a one-shot ?

Thanks again

**Comment by Poeschl** [comment]
Hi there, the addon is, as you already guessed it, designed as a one-shot.

If you want to execute the sync on a schedule you want to automate the addon start with Home Assistant Automation or some other System like Node Red.

Running it no a schedule is out of scope of the addon.
