### ISSUE TITLE
Syncthing 1.20.1 fails to start (HA 2022.5.5, HAOS 8.1)

### ISSUE THREAD

**Issue by kdorff** [Poeschl/Hassio-Addons#319]
**Which addon?**
syncthing

**Describe the bug**
After upgrading from 1.19.1 to 1.20.1, the logs show only `s6-overlay-suexec: fatal: can only run as pid 1`
Rolling back to 1.19.1 (using proxmox snapshots) brings syncthing back 1.19.1, which works.

**To Reproduce**

Notes:

- I'm **not** using the syncthing integration.
- I've repeated this 3 times with the same behavior.
- I am "up to date" with HA, HAOS, all other addons, etc.

Steps:

- Have syncthing addon 1.19.1 running.
- Look in `Settings | Addons | Syncthing | Logs` and see healthy log messages
- Take a snapshot with proxmox (so I can get back to a working system)
- upgrade syncthing to 1.20.1
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Restart syncthing from Look in `Settings | Addons | Syncthing | Restart`
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Reboot the VM with `Settings | System | Hardware | Reboot host`
- Wait for Reboot to complete to complete
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Restart syncthing from `Look in Settings | Addons | Syncthing | Restart`
- Look in `Settings | Addons | Syncthing | Logs` see  `s6-overlay-suexec: fatal: can only run as pid 1`
- Rollback the snapshot with proxmox (so my system works again).
- Reboot the system
- Look in `Settings | Addons | Syncthing` and see that syncthing is again at 1.19.1 and wanting to be updated.
- Look in `Settings | Addons | Syncthing | Logs` and see healthy log messages

**Expected behavior**
Log messages that show syncthing starting up / running.

**Screenshots**
N/A.

**System**
Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

**Comment by Poeschl** [comment]
If I'm understanding it correctly it's not an issue with one of the released addon versions.
It's an issue after changing the syncthing version and creating an custom addon version?

**Comment by kdorff** [comment]
@Poeschl it seems you are asking a question but I'm not following.

I'm running HA on HAOS. I am running Syncthing addon 1.19.1.
Within HA it is telling me I can upgrade to Syncthing 1.20.1.
The above procedure is what I followed when I accepted the update from HA for Syncthing 1.20.1.

And how after the upgrade, the logs for the syncthing addon only show `s6-overlay-suexec: fatal: can only run as pid 1`

You ask:
> It's an issue after changing the syncthing version and creating an custom addon version?

I'm not following you. I'm not doing anything with custom versions of anything.

HA is offering to upgrade from 1.19.1 to 1.20.1. I'm not doing anything related to custom versions or anything unusual. See attached three different places HA wants me to upgrade to a release version of 1.20.1.

![syncthing-addon-wants-upgrade-2](https://user-images.githubusercontent.com/757170/170389871-afb73b40-1bd5-48e1-8f06-fae9110a4a9f.jpg)
![syncthing-addon-wants-upgrade-1](https://user-images.githubusercontent.com/757170/170389873-286e7d79-8f3d-4924-9414-73a0febdd575.jpg)
![syncthing-addon-wants-upgrade-3](https://user-images.githubusercontent.com/757170/170389874-3507f064-55f4-49d2-a5ad-a3e20f4a4e26.jpg)

**Comment by kdorff** [comment]
Apologies. Apparently there are two different syncthing addons I'm using the other.

https://github.com/agileek/hassio-addons/issues/38

**Comment by kdorff** [comment]
Closing since it's not your problem.

**Comment by Poeschl** [comment]
All good 😉
I was just confused about addon versions which do not exist for my version. 🤣
