### ISSUE TITLE
Update valetudo-mapper version

### ISSUE THREAD

**Issue by ankisch** [Poeschl/Hassio-Addons#320]
**Which addon?**
valetudo-mapper

**Is your feature request related to a problem? Please describe.**
I would like to be able to use auto-calibration, https://github.com/rand256/valetudo-mapper/pull/6#issue-1131203992

**Describe the solution you'd like**
Update the addon to use the most recent version of valetudo-mapper

**Describe alternatives you've considered**

**Additional context**

**Comment by dimmuboy** [comment]
I'm not sure if it's official but we have here another version https://github.com/rand256/valetudo/issues/481

**Comment by Poeschl** [comment]
will be closed by e0271e926544b1bee671d2fe15a2da88e4f7f887
