### ISSUE TITLE
MPD does not work anymore 

### ISSUE THREAD

**Issue by Koendejongh** [Poeschl/Hassio-Addons#322]
**Which addon?**
MPD

**Describe the bug**
No sound through the Built-in audio stereo output (Raspberry PI)

**To Reproduce**
It seems not to work anymore since the introduction of VLC player by HA or version 2022.6.x.

**Expected behavior**
No sound, time out in log.

**Screenshots**
exception: CURL failed: Connection timeout after 10000 ms
exception: Failed to decode xxxxxxxxxxxxxxxxxxxxxxxxx my API link to mp3 file xxxxxxxxxxxxxxxxxxxxxxxx;
CURL failed: Connection timeout after 10007 ms

**System**
* Supervisor version: supervisor-2022.05.3
* Host system version :Home Assistant OS 8.2

**Comment by Poeschl** [comment]
Ahhh, not stale. But the maintainer (me) is busy in RL

**Comment by Poeschl** [comment]
Tested the existing addon with the latest HA OS / Home Assistant.

```
Home Assistant 2022.8.1
Supervisor 2022.07.0
Operating System 7.6
```

And it plays like expected. Via the web interface and also over HA with configured mpd integration.
It seems like the issue is not on the addon. Maybe your configuration needs to be changed after the update?
