### ISSUE TITLE
MPD not starting properly after recent update1.7.2 

### ISSUE THREAD

**Issue by Zeunas** [Poeschl/Hassio-Addons#339]
**Which addon?**
MPD

**Describe the bug**
First I would like to thank you for sorting out the issue regarding ` s6-overlay-suexec: fatal: can only run as pid 1.`  references #335 and #336 .
However something is still not working right, when I start MPD it gives me the below log as expected:

`[22:54:13] INFO: Setup Folders
[22:54:14] INFO: Setup settings
[22:54:15] INFO: Set media folder
[22:54:15] INFO: Set playlist folder
[22:54:16] INFO: Start MPD
exception: Failed to open '/data/database/mpd.db': No such file or directory
[22:54:16] INFO: Start ympd
MPD Connecting to 127.0.0.1:6600
MPD connected.
`

But these are the issues I encounter:

- MPD add-on is showing as not having even started, see below snapshot:
![image](https://user-images.githubusercontent.com/71456261/185336978-8305aedb-88a5-4b73-bd61-27d1504df89c.png)

- When trying to access the side panel I get the below error:
![image](https://user-images.githubusercontent.com/71456261/185337264-8f6d14d4-b19f-4c77-bb85-c8c168ca9c66.png)

- Any changes I make on the Configuration tab of the add-on are not reflected

With all of these I am still able to use the below platform and use media_player.play_media

`media_player:
  - platform: mpd
    host: 243ffc37-mpd
    port: 6600`

**To Reproduce**
1. Start MPD
2. Check Logs
3. Check side bar
4. Use media_player mpd platform as per above

**Expected behavior**
MPD to start properly with all the functions

**System**
Home Assistant 2022.8.5
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest

**Comment by akarpych** [comment]
Confirm. The same problem.

**Comment by Zeunas** [comment]
Surprised this worked but I just uninstalled it, rebooted the host and installed it again and it did the trick.

**Comment by Poeschl** [comment]
Uh, OK.
Thanks for reporting back. 👍
