### ISSUE TITLE
[syncthing] GUI authentication warnings

### ISSUE THREAD

**Issue by salim-b** [Poeschl/Hassio-Addons#340]
### Which addon?

syncthing

### Problem description

After startup, Syncthing displays a big red non-dismissable "Danger!" banner saying its admin interface would be configured "to allow remote access without a password" and asking to set up a username and password.

This banner was added to Syncthing in https://github.com/syncthing/syncthing/pull/2478 and is displayed whenever the Syncthing admin interface (GUI) is configured to listen on an address other than `127.0.0.1` (this add-on configures Syncthing to listen on [`0.0.0.0:8384`](https://github.com/Poeschl/Hassio-Addons/blob/main/syncthing/root/etc/s6-overlay/s6-rc.d/syncthing/run#L10) and the normal GUI port is [disabled](https://github.com/Poeschl/Hassio-Addons/blob/main/syncthing/config.yaml#L17) and thus not reachable from outside the Home Assistant host).

As far as I understand, the danger banner is

1. incorrect in case of this add-on since the Syncthing GUI is only accessible from within the Home Assistant host and securely embedded into Home Assistant's GUI via [Ingress](https://developers.home-assistant.io/docs/add-ons/presentation/#ingress).

   The Ingress doc explicitly [states](https://developers.home-assistant.io/docs/add-ons/presentation/#ingress):

   > Users are previously authenticated via Home Assistant. Authentication is not required.
 
   So there should be really no need to further secure access.

2. potentially dangerous since web browsers (at least Firefox) get confused and fail to properly load the Syncthing GUI embedded into Home Assistant's GUI if Syncthing GUI credentials are set (they mess up credentials caching or the like). At least this is what I experienced when I first set up a username and password for the Syncthing GUI: After reloading the Home Assistant GUI, the Syncthing GUI wasn't loaded anymore, but *no* password prompt was displayed either. Others apparently [ran into the same issue](https://community.home-assistant.io/t/syncthing-addon/320452/12).

### Possible solution

There's an advanced config option **`insecureAdminAccess`** in Syncthing that disables the red danger banner and instead triggers a lower severity dismissable yellow warning about this option being enabled. We could set `insecureAdminAccess="true"` by default. The yellow warning would still be annyoing (and confusing) but less dangerous since users are not inclined to configure another pointless layer of credentials which has the potential to (temporarily) lock them out of the Syncthing GUI.

In the medium term, Syncthing devs might even be open to add the [possibility to completely suppress the warning](https://github.com/syncthing/syncthing/pull/2478#discussion_r45117560). Maybe we should ask politely?

**Comment by salim-b** [comment]
Additional question: The Ingress doc also says that

> Only connections from `172.30.32.2` must be allowed. You should deny access to all other IP addresses within your add-on server.

But the currently configured address `0.0.0.0` means to listen on ["all IPv4 addresses on the local machine"](https://superuser.com/a/949522/666946), right? Could we change the [startup option](https://github.com/Poeschl/Hassio-Addons/blob/main/syncthing/root/etc/s6-overlay/s6-rc.d/syncthing/run#L10) to `-gui-address=172.30.32.2:8384` instead?

**Comment by Poeschl** [comment]
I will try both suggestions 😉

But it may take a while

**Comment by salim-b** [comment]
Still relevant.

**Comment by salim-b** [comment]
Still relevant

**Comment by reedy** [comment]
> But the currently configured address `0.0.0.0` means to listen on ["all IPv4 addresses on the local machine"](https://superuser.com/a/949522/666946), right? Could we change the [startup option](https://github.com/Poeschl/Hassio-Addons/blob/main/syncthing/root/etc/s6-overlay/s6-rc.d/syncthing/run#L10) to `-gui-address=172.30.32.2:8384` instead?

We can't hard code the IP to "172.30.32.2", but we can obviously get it from the system (something like `ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}'` from a quick search) and pass that through to the script as a parameter...?

**Comment by salim-b** [comment]
> There's an advanced config option **`insecureAdminAccess`** in Syncthing that disables the red danger banner and instead triggers a lower severity dismissable yellow warning about this option being enabled. We could set `insecureAdminAccess="true"` by default. The yellow warning would still be annyoing (and confusing) but less dangerous since users are not inclined to configure another pointless layer of credentials which has the potential to (temporarily) lock them out of the Syncthing GUI.

This config option can be set via the following CLI command while Syncthing is running:

```sh
syncthing cli config gui insecure-admin-access set true
```

So I guess we could simply run that command right *after* [launching syncthing](https://github.com/Poeschl/Hassio-Addons/blob/main/syncthing/root/etc/s6-overlay/s6-rc.d/syncthing/run#L20). What do you think @Poeschl?
