### ISSUE TITLE
MaryTTS No such file or directory

### ISSUE THREAD

**Issue by mundeczek** [Poeschl/Hassio-Addons#345]
Installed add-on, first start and in log file:

> s6-rc-compile: fatal: unable to read /etc/s6-overlay/s6-rc.d/marytts/type: No such file or directory

Reinstallation didn't help

 System: Ubuntu 20.04.5 LTS  (amd64 / qemux86-64)
 Home Assistant Core: 2022.8.7
 Home Assistant Supervisor: 2022.08.5

**Comment by Poeschl** [comment]
Fixed by ea05d30461687bb4d3f0d95c4463f0ca6f169c6a and Version 1.5.2 of addon.
