### ISSUE TITLE
HACS-support?

### ISSUE THREAD

**Issue by exetico** [Poeschl/Hassio-Addons#35]
Hi, 

I just spotted this, and find it pretty awesome.

However, would it be possible to integrate it with [HACS](https://community.home-assistant.io/t/custom-component-hacs/121727), instead of Hassio? :-)

I would just like to hear, if that's an option. Maybe someone are already working on it.

**Comment by Poeschl** [comment]
Those add-ons require their own software installations including dependencies which are not part of the homeassistant. So its not possible to migrate them over to HACS. 

HACS Plugins / Integrations are adding functionality inside homeassistant with available python dependencies and the ability to install required ones.
As soon something needs to be installed on system level, Hass.io Addons are the way to go. 😉

**Comment by exetico** [comment]
Oh, that's good point. I didn't think og the requirements. I'll find
another way to do it, instead. I guess it would make to have it in a
container, or so - but, maybe it's already done. I'll check that tomorrow.

And oh, thanks for the fast reply. It's always nice to have both better
replies and faster response-times, than most companies have.

tor. 19. dec. 2019 17.47 skrev Markus Pöschl <notifications@github.com>:

**Comment by Poeschl** [comment]
Hass.io Addons are already containers which everything inside. 😉
Inside HACS you can "only" use the python environment.

I will close this issue. Nevertheless if you find a nice way, Let me know 😉

**Comment by exetico** [comment]
Wow. I'm not sure how i missed the fact that Hass.io's addons is containers :-D I'm running HA on a dedicated server, but as a container. I'll let you know, if i find something..

Happy Christmas - and thanks for the fast answer. I'm sorry for waiting a bit of your time :D

**Comment by Poeschl** [comment]
Merry Christmas🎄
Its not wasting if it helps you. 😉
