### ISSUE TITLE
[ympd] MPD password?

### ISSUE THREAD

**Issue by corvin78** [Poeschl/Hassio-Addons#354]
**Which addon?**

ympd - mpd password authentication

**Is your feature request related to a problem? Please describe.**

When I try to access user interface I got 502: Bad gateway

**Describe the solution you'd like**

I think it is the problem with no password for mpd in ympd addon configuration.

**Describe alternatives you've considered**

Disable MPD password authentication? (I do not wish to do that, but I could check if it works..)

**Additional context**

**Comment by corvin78** [comment]
Additional info: When I disable password authentication I still cannot access user interface of ympd addon with same error: 502: Bad gateway.

**Comment by Poeschl** [comment]
@corvin78 Do you have an log output of your case?
It tested it out myself on a fresh install of the addon and an mpd server. But the Web-UI came up in every case. Saying that it can't connect but came up.
