### ISSUE TITLE
[syncthing] Make addon work with integration

### ISSUE THREAD

**Issue by Poeschl** [Poeschl/Hassio-Addons#357]
**Which addon?**

Syncthing

**Is your feature request related to a problem? Please describe.**

The addon should work with the HA integration

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

See Homeassistant Post on forum.

**Comment by Poeschl** [comment]
closed by mistake.

Note for me: https://community.home-assistant.io/t/syncthing-addon/320452/7?u=poeschl

**Comment by reedy** [comment]
Looks like my #414 is somewhat of a dupe/overlap...
