### ISSUE TITLE
Strange map colors

### ISSUE THREAD

**Issue by fillilutten** [Poeschl/Hassio-Addons#37]
**Which addon?**
Valetudo Mapper

**Describe the bug**
Just did a default installation and it works but the colors seems really off. And I couldn't figure out how to change background color or the colors off the walls. I want it to look something blueish like in the Valetudo web ui but could only change the floor color, not the lime green walls or the grey background.

**Screenshots**
[https://imgur.com/a/YGjl99j](url)

**Comment by Poeschl** [comment]
Since the addon just embed the [Valetudo-Mapper](https://github.com/rand256/valetudo-mapper) and don't change anything about the rendering and such, I think the issue can be found there.

Maybe @apoc4lyps is kind and could take a look?

**Comment by apoc4lyps** [comment]
@fillilutten which firmware do you have installed (https://github.com/rand256/valetudo or https://github.com/Hypfer/Valetudo)? Can you check the map direct from the addon?

**Comment by fillilutten** [comment]
> @fillilutten which firmware do you have installed (https://github.com/rand256/valetudo or https://github.com/Hypfer/Valetudo)? Can you check the map direct from the addon?

This is what my settings look like in the add on. 
https://ibb.co/PQzZz6h

I m running the latest rand265 fork. Re8.

**Comment by apoc4lyps** [comment]
those settings look correct. did you verify the map rendering on the valetudo interface? maybe clear the persistent data on the vacuum.

![image](https://user-images.githubusercontent.com/10954235/71644889-14ae2c00-2cd0-11ea-93fd-eb8df078f39f.png)

**Comment by fillilutten** [comment]
By validate you mean look in valetudo so the map looks ok there? Yes it worked perfect. The map got deleted since I accidentally did a spot clean but made a Start cleaning to rescan the apartment again. The map seems correct but the new map is that green/black anyway.

**Comment by apoc4lyps** [comment]
Strange, Colors are hardcoded within the node app. As a last idea I would delete the MQTT data from Valetudo and the addon. After that restart Valetudo and the addon.

**Comment by fillilutten** [comment]
I'm S T U P I D! It's the lovelace map card that acting like this. I've mixed them up and yours is working perfect, so sorry for all the trouble. Now I'll have to sort out why the xiaomi lovelace map card is acting like that. 

Thanks once more!

**Comment by Poeschl** [comment]
I'm closing the issue.

Thanks @apoc4lyps for helping out. 👍
