### ISSUE TITLE
make map transparent

### ISSUE THREAD

**Issue by thundergreen** [Poeschl/Hassio-Addons#38]
**Which addon?**
The title of the addon the new feature is for.
Valetudo Mapper
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem

![image](https://user-images.githubusercontent.com/13320319/72679164-d5902100-3aac-11ea-9060-204e826326f2.png)
 is. Ex. I'm always frustrated when [...]
I'd like aving the map as transparent like the Icantbeliveitsnotvaletudo addon.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
The Addon only provides the [Valetudo-Mapper](https://github.com/rand256/valetudo-mapper/blob/master/README.md) for HassIO.

For issues and requests about the mapper itself look for help there. 😉
