### ISSUE TITLE
rsync: missing dash in "-archive"

### ISSUE THREAD

**Issue by oliverrahner** [Poeschl/Hassio-Addons#380]
**Which addon?**
rsync

**Describe the bug**
In https://github.com/Poeschl/Hassio-Addons/blob/a8990b1192340412276486cc36a50153c9ce9d20/rsync/root/run.sh#L32, an option `-archive` is present. I _believe_ that actually `--archive` was meant.
This effectively turns on the following options:
- `-a, --archive`: is the one we _actually_ want
- `-r, --recursive`: is already turned on by `-a` 
- `-c, --checksum`: **This is very bad! It means that every file has to be read as a whole on both the source and the destination to determine whether a file should be synced!** Leads to unnecessary I/O load.
- `-h, --human-readable`: output only, doesn't matter
- `-i, --itemize-changes`: output only, doesn't matter
- `-v, --verbose`: output only, doesn't matter
- `-e, --rsh`: _should_ be bad, because it tries to replace the remote shell command... don't know why it works nevertheless :)

**To Reproduce**
Trigger `rsync`, watch `iotop` or `top` on the target machine

**Expected behavior**
Replace option by `--archive`, removing the `-c` option

**Screenshots**
![image](https://user-images.githubusercontent.com/2277681/221126761-becc2509-d57b-443a-bf94-c3250210ed06.png)

**System**
(Bug found in source, versions shouldn't matter)
Home Assistant 2023.2.1
Supervisor 2023.01.1
Operating System 9.5

**Comment by Poeschl** [comment]
Nice finding. 👍
Will correct it on the next fixing run.

**Comment by sergiosamy** [comment]
I also see that "-archive" wrong option as well I could not make this addon work even passwordless:

[17:54:17] INFO: Use private key from /ssl/rsync/id_rsa
[17:54:21] INFO: Sync /config -> /home/tmp with options "-archive --recursive --compress --delete --prune-empty-dirs"
++ rsync -archive --recursive --compress --delete --prune-empty-dirs -e 'ssh -p 22 -i /ssl/rsync/id_rsa -oStrictHostKeyChecking=no' /config myuser@10.0.0.141:/home/tmp
Warning: Permanently added '10.0.0.141' (ED25519) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
myuser@10.0.0.141: Permission denied (publickey,password).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]
