### ISSUE TITLE
rsync-local - Please add "sdc1" to available options

### ISSUE THREAD

**Issue by cholek3** [Poeschl/Hassio-Addons#381]
**Which addon?**

rsync-local

**Is your feature request related to a problem? Please describe.**

I have a 3rd drive I would like to sync to. 3rd drive is sdc1. When trying to add `sdc1` to `external_device`, log returns an error:
```
[10:58:17] INFO: Starting sync...
[10:58:17] INFO: Mounting device /dev/sdc1
mount: permission denied (are you root?)
```
**Describe the solution you'd like**

Please add "sdc1" (maybe more?) to available options of `external_device` config.

**Comment by googanhiem** [comment]
Don't think Poeschl has the time for new features, but I've built on his fantastic rsync-local, adding a bunch of features (including sdc support). I've renamed it [usb-backup](https://github.com/googanhiem/gords-ha-addons/tree/main/usb-backup) as some people won't know how great rsync is.

**Comment by reedy** [comment]
In theory, `/dev/[hsv]d[a-z][1-9]` would be needed to cover all cases (though, I suspect 9 might not be enough in some either)...

We can do regex in `external_device`, but I'm presuming they need to be listed in `devices` too?

**Comment by googanhiem** [comment]
I'll try adding that to my version. Thanks @reedy
