### ISSUE TITLE
Home Assistant Git Exporter : schedule runs

### ISSUE THREAD

**Issue by davidszerman** [Poeschl/Hassio-Addons#388]
**Which addon?**
Home Assistant Git Exporter

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Having a service in HA to run the git exporter based on a schedule or any trigger I want

**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
That's something you can do with automations and the addon services 😉
