### ISSUE TITLE
Syncthing: Sync Protocol Listen Addresses don't work

### ISSUE THREAD

**Issue by MuellerNicolas** [Poeschl/Hassio-Addons#393]
**Which addon?**
[syncthing](https://github.com/Poeschl/Hassio-Addons/tree/main/syncthing)

**Describe the bug** / **To Reproduce**
Under "Actions"->"Settings" -> "Connections", it is possible to set the [Sync Protocol Listen Addresses](https://docs.syncthing.net/v1.23.3/users/config#listen-addresses). When setting this input to `tcp://192.168.178.21:22000` or rather `tcp4://192.168.178.21:22000`, i get the following error message (after clicking on "Listeners 0/1"):
```
Listener Failures
Syncthing is not listening for connection attempts from other devices on any address. Only outgoing connections from this device may work.

Some listening addresses could not be enabled to accept connections:

tcp://192.168.178.21:22000: listen tcp 192.168.178.21:22000: bind: cannot assign requested address
```
The log output is as followed:
`2023-04-22 23:49:25 Listen (BEP/tcp): listen tcp 192.168.178.21:22000: bind: cannot assign requested address`

I also found out that setting it to the local loopback device `tcp://127.0.0.1:22000` works fine, but the other devices are not able to connect to it:

```
dial tcp 192.168.178.21:22000:
connectex: Es konnte
keine Verbindung
hergestellt werden, da
der Zielcomputer die
Verbindung verweigerte
```
(says that `192.168.178.21:22000` refused the connection)

Is there any mapping of ip-addresses necessary, because the docker container does not know it's host ip? Or am I missing something crucial here?

**EDIT:**
_When setting it to `tcp://0.0.0.0:22000` the connection was possible. I don't quite understand how this is possible... Also from the logs i could see that it connecting to the containers ip `172.30.33.5`. So i tried to set `tcp://172.30.33.5:22000` (should be a private ip and therefore the one of docker??) and it worked as well._
I don't like this so i would be happy if there is a solution to use the real ip address of my home assistant.

**Expected behavior**
The device should be able to listen to it's own ip address.

**Screenshots**

**System**

* Supervisor version: 2023.04.0
* Host system version: 10.0

Thank you very much for your support :)

**Comment by Poeschl** [comment]
If the address is empty it will accept all connections inside the docker container. So it will accept also the request which are mapped through Home Assistant OS.
The IP from which those routed requests are coming is the `172.30.32.2`. (as far as I know)

The syncthing executable should be discoverable without any additional configuration in the gui.

**Comment by MuellerNicolas** [comment]
Thank you for your quick response 😊
Well in case you are wondering why i'm trying to configure this: My goal is to use Syncthing completely local in my home network. So I do not want Syncthing to use external connections to a relay for example or even be discoverable externally. I know everything is encrypted in syncthing, but it gives me a better feeling, knowing no data leaves my local home network.

1. Setting "Sync Protocol Listen Addresses" empty, leads to the problem that the devices can't establish a connection - i/o timeout. It show the warning: `Listener Status: Syncthing is not listening for connection attempts from other devices on any address. Only outgoing connections from this device may work.`
2. Can I set it to 172.30.32.2 permanently? At the moment this works fine, but will restarts influence this ip? I have no clue how the ip setup in the syncthing docker container works, could you please give me a short insight?
3. 172.30.32.2 is a internal ip address only visible in my local network. Am i right?
4. Yes, without additional configuration in the gui it was also working, because the [Default listen addresses (default)](https://docs.syncthing.net/v1.23.3/users/config#listen-addresses) are containing `tcp://0.0.0.0:22000`.

**Comment by Poeschl** [comment]
To your questions:
* All settings you making are persistent between restarts of the addon. Only re-installing will delete them.
* The 172.* ips are internal IPs of the internal Home Assistant OS system. They are not available from outside your HA host.

From my understanding of the syncthing settings (and my access logs from): To reach an local only instance it is enough to disable the global device search and NAT traversal features. Without NAT on your router it won't be able to get accessed from outside your network.

Snapshot of my settings:
![image](https://user-images.githubusercontent.com/5469257/233836526-fe0e3201-9444-408f-9f2e-9f39f535f8d1.png)

**Comment by MuellerNicolas** [comment]
- A further explanation of this setting can be found [here](https://forum.syncthing.net/t/further-information-about-listen-addresses-tcp4-0-0-0-0-22000/20118?u=mondmonarch)
- Genereal information about settings to have your syncthing instance on your local network only can be found [here](https://forum.syncthing.net/t/limit-syncthing-to-only-use-local-network-review-and-suggestions-appreciated/20117?u=mondmonarch)
