### ISSUE TITLE
https - ssl

### ISSUE THREAD

**Issue by chaimt** [Poeschl/Hassio-Addons#4]
an option for ssl is needed so that i can add it as an iframe

**Comment by Poeschl** [comment]
For which one of the plugins you're asking for?

I assume it's the `ICantBelieveItsNotValetudo` one, where I'm just wrapping the original software from [Hypfer/ICantBelieveItsNotValetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo) into a docker container.

**Comment by chaimt** [comment]
Yes that is the one

**Comment by Poeschl** [comment]
Would #6 also be a option for you? To use HA's ingress feature for serving the image out.

**Comment by Poeschl** [comment]
Will be fixed with #6
