### ISSUE TITLE
Map not showing

### ISSUE THREAD

**Issue by jlo88** [Poeschl/Hassio-Addons#40]
I've been using the icantbelieveitsnotvaletudo add-on for a while now but it stopped updating the map in home assistant. 

Looking with mqtt explorer shows the following map data: https://hastebin.com/yuyeyodimu.json updated 10 minutes ago.

However, nothing shows in home-assistant, the ingress tab shows `Not Found` 

These are the addon settings: 

```
{
  "identifier": "rockrobo",
  "topicPrefix": "valetudo",
  "autoconfPrefix": "homeassistant",
  "broker_url": "mqtt://username:password@hassio.local",
  "caPath": "",
  "mapSettings": {
    "drawPath": true,
    "drawCharger": true,
    "drawRobot": true,
    "border": 2,
    "scale": 4
  },
  "mapDataTopic": "valetudo/rockrobo/map_data",
  "minMillisecondsBetweenMapUpdates": 10000,
  "publishMapImage": true
}
```

The log shows: 

```
[19:02:53] INFO: Setup config
[19:02:53] INFO: Start ICantVelieveItsNotValetudo

> i-cant-believe-its-not-valetudo@0.2.0 start /app
> node app.js

Loading configuration file: /app/config.json
Connecting to MQTT Broker
Webserver running on port 3000
```

I just re-installed the add-on, no change. 

add-on version: 0.2.0-5

home-assisant info: 

```
arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.6
timezone | Europe/Amsterdam
version | 0.104.3
virtualenv | false
```

host system: Ubuntu 19.10

**Comment by Poeschl** [comment]
You replaced the username and password in the `broker_url` ? And your Home Assistant is available under `hassio.local`?

**Comment by jlo88** [comment]
Hmm, I replaced hassio.local with the real IP address and now it works, apparently it couldn't resolve? Thanks for the answer!
