### ISSUE TITLE
Link "web UI" in DOCS.md

### ISSUE THREAD

**Issue by reedy** [Poeschl/Hassio-Addons#415]
**Which addon?**
syncthing; maybe others?

**Is your feature request related to a problem? Please describe.**
https://github.com/Poeschl/Hassio-Addons/blob/18b96cc/syncthing/DOCS.md#configuration doesn't have a link to the Web UI, nor is it overly clear (for people that may be new-er to HA) where they might find the link.

**Describe the solution you'd like**
Ideally, make `web UI` in DOCS.md a clickable link.

And/or document that a user can use "OPEN WEB UI" from the `Info` tab rather than just saying "configure it there"

**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
Feel free to make an PR 😉

**Comment by reedy** [comment]
The second part is easier...

The first, is `/ingress/243ffc37_syncthing` considered "stable" (I don't know where the hash prefix comes from).

It looks like it might be with others referencing it in https://community.home-assistant.io/t/syncthing-open-web-ui-not-working/369342 etc

**Comment by reedy** [comment]
PR does the documenting... Doesn't do the linking

**Comment by salim-b** [comment]
> The first, is `/ingress/243ffc37_syncthing` considered "stable" (I don't know where the hash prefix comes from)?

I think so. But I can't tell where exactly the prefix comes from... @Poeschl ?

**Comment by Poeschl** [comment]
The prefix seem to be the hash of the add-on source repository. As far as I know
