### ISSUE TITLE
Unable to install Valetudo mapper in the latest version, "manifest unknown"

### ISSUE THREAD

**Issue by p1ranha** [Poeschl/Hassio-Addons#42]
**Which addon?**
Valetudo Mapper

**Describe the bug**
When installing Valetudo mapper in hassio addons following error appears:

> Failed to install addon, Unknown Error, see logs.

In the logs, following entries are visible:

> 20-02-07 08:22:51 INFO (MainThread) [hassio.addons] Create Home Assistant add-on data folder /data/addons/data/7d80160c_valetudomapper

> 20-02-07 08:22:51 INFO (SyncWorker_10) [hassio.docker.interface] Pull image poeschl/hassio-valetudo-mapper-amd64 tag 1.1.0.

> 20-02-07 08:22:52 ERROR (SyncWorker_10) [hassio.docker.interface] Can't install poeschl/hassio-valetudo-mapper-amd64:1.1.0 -> 404 Client Error: Not Found ("manifest for poeschl/hassio-valetudo-mapper-amd64:1.1.0 not found: manifest unknown: manifest unknown").

**To Reproduce**
Install or update hassio addon.

**Comment by dwainscheeren** [comment]
Got the same error `Failed to install addon, Unknown Error, see logs`

**Comment by apoc4lyps** [comment]
there are problems with the built. I'm already looking for the issue.

**Comment by foXaCe** [comment]
same problem for me on RPI4

ERROR (SyncWorker_7) [hassio.docker.interface] Can't install poeschl/hassio-valetudo-mapper-armv7:1.1.0 -> 404 Client Error: Not Found ("manifest for poeschl/hassio-valetudo-mapper-armv7:1.1.0 not found: manifest unknown: manifest unknown").

**Comment by Poeschl** [comment]
Should be fixed as soon e106e35 is has been build. [Build Status](https://travis-ci.org/Poeschl/Hassio-Addons/jobs/647470904)

**Comment by apoc4lyps** [comment]
Issue should be fixed. I was able to update to version 1.1.0 (amd64)

**Comment by Poeschl** [comment]
Than this is closed. Thanks for the fast fix @apoc4lyps
