### ISSUE TITLE
CI failure when building add ons...

### ISSUE THREAD

**Issue by reedy** [Poeschl/Hassio-Addons#428]
Seems to be broken on various different add on builds..

**Comment by Poeschl** [comment]
The broken thing is the package management of alpine. 😅

For the build test, the apk packages must exist at the specified version. Since alpine only keep the last version the build get red when at least one package is out of date.

**Comment by reedy** [comment]
Is there not a better way to handle it?

**Comment by Poeschl** [comment]
@reedy I could go to remove a specific version of the system packages, but then by always using "latest" a build is not reproducable and might introduce new issues without notice.

Downside on the current way: when changing anything and there are new packages, the build breaks.

Pro: The version update needs to be made by hand, tested the function and provides a stable addon.

**Comment by reedy** [comment]
It'd be useful if there was a bot or something that monitored for new packages, and at least created an issue, and/or a PR and see if the CI works...

Arguably, that's not full testing, I know...

You could do the inbetween, and not specify the the `-r[0-9]`; which in theory should only be underlying package rebuilds...

Though, looking at https://git.alpinelinux.org/aports/log/community/syncthing, most of the `-r` builds end up being bumping go versions, which probably could cause more problems than updating the package itself.

🍿
