### ISSUE TITLE
Reinstate mitmproxy

### ISSUE THREAD

**Issue by davet2001** [Poeschl/Hassio-Addons#429]
**Which addon?**

Mitmproxy

**Is your feature request related to a problem? Please describe.**

Feature request

**Describe the solution you'd like**

Un-deprecate the addon

**Describe alternatives you've considered**

Creating the an mitmproxy addon myself from scratch

**Additional context**

Mitmproxy is great for adblocking :)

**Comment by davet2001** [comment]
I'd really love for mitmproxy to be available again, and it seems that you are the only one that's made an addon for it.   Perhaps I could help by submitting some PRs to get it up and running again?  Please let me know your thoughts.

**Comment by Poeschl** [comment]
Since reinstating the mitmproxy addon has a hight effort for myself, for only a little use, this will not happen. Sry, but it's an hobby and I'm already short on time for the other add-ons. 😅 

If you want to revive it, fork the sources and maintain it yourself 😉

**Comment by davet2001** [comment]
Ok understood - that is totally fine. 

Probably I cannot do a conventional fork because I would add it to my own adding repo with existing things in it, but would copy paste and reference back.  Are you ok with that?

**Comment by Poeschl** [comment]
@davet2001 That's totally fine 😊
When you give me a link, I will add it in the Readme here as well.

**Comment by Meister1977** [comment]
hi @davet2001 , have you forked? I would like to add to my HA too.

**Comment by davet2001** [comment]
> hi @davet2001 , have you forked? I would like to add to my HA too.

In progress, not ready yet!

**Comment by davet2001** [comment]
@Poeschl I have it mostly working, but I have a question: what is the reverse proxy for in the addon?  I removed this and found it worked ok, directly exposing port 8080 for the regular webproxy, and port 8081 for the web configuration page.

I couldn't work out why the reverse proxy had been included.  Please could you help me understand?

**Comment by davet2001** [comment]
Ok, thanks, yes, I see.  https://github.com/mitmproxy/mitmproxy/issues/4033

**Comment by davet2001** [comment]
mitmprox addon is now working and available for install!

Please consider it beta at the moment. There are a few more weirdities that I need to work out, but do submit issues to the issue tracker on the repo linked below.

https://my.home-assistant.io/redirect/_change/?redirect=supervisor_add_addon_repository%2F%3Frepository_url%3Dhttps%253A%252F%252Fgithub.com%252Fdavet2001%252Fhome-assistant-addons

**Comment by davet2001** [comment]
It's working now!

https://github.com/davet2001/home-assistant-addons/tree/main/mitmproxy
