### ISSUE TITLE
[valetudo-mapper] MQTT entities naming for Home Assistant guidelines

### ISSUE THREAD

**Issue by Bodengriller** [Poeschl/Hassio-Addons#449]
**Which addon?**
valetudo-mapper

**Describe the bug**
Starting with Home Assistant 2023.8.0 a warning about entities naming that will stop working in upcoming release (2024.2).

More information [The naming of MQTT entities changes to correspond with HA guidelines](https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/)

See also [this issue](https://github.com/rand256/valetudo/issues/506) and [this solution](https://github.com/rand256/valetudo/issues/506#issuecomment-1721764189)
I think the addon should just be updated to the current docker image of valetudo-mapper?

**To Reproduce**

Install Home Assistant 2023.8 or greater with MQTT'...'
Setup MQTT at vacuum
Discover and add device to MQTT
See warning at Home Assistant settings page

**Expected behavior**
Devices are discovered and no warning is shown.

**Screenshots**
<img width="1134" alt="image" src="https://github.com/Poeschl/Hassio-Addons/assets/50927649/edbe5336-e48f-43c3-8e10-76dd83b12374">

**Comment by Bodengriller** [comment]
> Hi, there.
> 
> Please make sure you have the right addon for your software. The addon you mentioning is the companion for [Valetudo RE from rand256](https://github.com/rand256/valetudo).
> 
I'm sure :)
<img width="863" alt="image" src="https://github.com/Poeschl/Hassio-Addons/assets/50927649/47b200a3-867e-40d0-8af7-b99355b70048">

**Comment by Poeschl** [comment]
Will be closed by #452
