### ISSUE TITLE
[syncthing] Mount only `/media`, `/share` and `/backups`

### ISSUE THREAD

**Issue by salim-b** [Poeschl/Hassio-Addons#458]
I [was wondering](https://github.com/Poeschl/Hassio-Addons/pull/450#issuecomment-1873531727) whether we should **limit** the mounts (`map` in `config.yaml`) by

- mounting `ssl` read-only, i.e. remove the `:rw`, or even completely removing `ssl`. Why does Syncthing need access to custom certs in the first place? We have Ingress for that, no?
- removing `addons:rw`. What is the use case for Syncthing having access to local add-ons? Not even the official *File editor* add-on [has access to `addons`](https://github.com/home-assistant/addons/blob/master/configurator/config.yaml) since it's [deemed confusing for non-developers](https://github.com/home-assistant/addons/issues/2608#issuecomment-1207298460).

**Comment by salim-b** [comment]
We should reconsider this since people actually like to sync HA-internal files, [it appears](https://github.com/Poeschl/Hassio-Addons/issues/460). So maybe even do the opposite of the above and expose `all_addon_configs:rw` and `homeassistant_config:rw`, too?

**Comment by Poeschl** [comment]
I would suggest that we enable the mount but add a warning in the addon Readme about the security risk.

**Comment by jwinston100** [comment]
I would just like to second the idea of allowing exposure to /config perhaps with a warning, as I personally have been using Syncthing to edit files in /config via other devices.

**Comment by salim-b** [comment]
> I would suggest that we enable the mount but add a warning in the addon Readme about the security risk.

That sounds reasonable.

I think that people could generally use some guidance with the different persistent directories available to Syncthing. Maybe we should just include a table similar to [this one](https://github.com/home-assistant/addons/blob/master/samba/DOCS.md#connection) with a short explanation of each dir? Unfortunately, the [official documentation](https://developers.home-assistant.io/docs/add-ons/configuration/#optional-configuration-options) about these dirs (documented under the `map` key) is very sparse, so just linking to it is not really an option.

**Comment by Poeschl** [comment]
@salim-b The table is a nice idea. That would be a great thing to have.

**Comment by MJeka** [comment]
How to sync /config folder? I have several redundant servers that need to have up-to-date information with automatic synchronization of configuration files

**Comment by alucryd** [comment]
Being able to sync `/config` would be great indeed, that was the sole reason I looked into a syncthing add-on in the first place.

**Comment by jwinston100** [comment]
I agree with @alucryd. I had mentioned this issue [before](https://github.com/Poeschl/Hassio-Addons/issues/460). The `/config` directory is the only one I have ever used, as it lets me edit automations.yaml, configuration.yaml, etc. on other devices. I had to roll back to a previous version and turn off auto-update. I hope a future version allows us to access that directory.

**Comment by salim-b** [comment]
> @salim-b The table is a nice idea. That would be a great thing to have.

See https://github.com/Poeschl/Hassio-Addons/pull/467.

**Comment by jwinston100** [comment]
Thank you @salim-b for helping to fix this issue!

**Comment by zoe-codez** [comment]
Stumbled across this conversation trying to get at the home assistant config also. How does mounting the home assistant `/config` folder interact with syncthing's own `/config` folder? You get warnings when 


There are already files in that folder, and they seem like the type syncthing would want to keep around

- cert.pem
- config.xml
- config.xml.v0
- https-cert.pem
- https-key.pem
- key.pem
