### ISSUE TITLE
Error on install - PicoTTS 1.04

### ISSUE THREAD

**Issue by Smith754** [Poeschl/Hassio-Addons#49]
**Which addon?**

PicoTTS 1.04

**Describe the bug**

Just get an error (see below) when trying to install new PicoTTS 1.04.

**To Reproduce**

Got the following error in system logs:
20-02-08 17:54:44 ERROR (SyncWorker_4) [hassio.docker.interface] Can't install poeschl/hassio-picotts-amd64:1.0.4 -> 404 Client Error: Not Found ("manifest for poeschl/hassio-picotts-amd64:1.0.4 not found").

**Expected behavior**

Didn't install.

**Screenshots**

Cheers!  Hope it gets fixed.

**Comment by Poeschl** [comment]
Looks like the build screwd up again, will look at it today 😉

**Comment by Poeschl** [comment]
Will be fixed when 4b33640f93e11d9e3c54a6bff9c1e2163efd89ba has been build. [Buildstatus](https://travis-ci.org/Poeschl/Hassio-Addons/jobs/647978803)
