### ISSUE TITLE
ICantBelieveItsNotValetudo: addon is not starting, error 400 in console

### ISSUE THREAD

**Issue by bbbenji** [Poeschl/Hassio-Addons#5]
Installed the addon and configured it:
```
{
  "identifier": "rockrobo",
  "topicPrefix": "valetudo",
  "autoconfPrefix": "homeassistant",
  "broker_url": "mqtt://USER:PASS@IP",
  "caPath": "",
  "mapSettings": {
    "drawPath": true,
    "drawCharger": true,
    "drawRobot": true,
    "border": 2,
    "scale": 4
  },
  "mapDataTopic": "valetudo/rockrobo/map_data",
  "minMillisecondsBetweenMapUpdates": 10000,
  "publishMapImage": true
}
```

Unable to start the addon, logs in the addon's config are empty and home-assistant logs do not mention anything either. Browser console log shows:
```
Failed to load resource: the server responded with a status of 400 ()  /api/hassio/addons/243ffc37_icantbelieveitsnotvaletudo/start:1 
```

**Comment by bbbenji** [comment]
RESOLVED

Grafana addon was using the same port (3000). Perhaps ICantBelieveItsNotValetudo should use a different default port?

https://github.com/hassio-addons/addon-grafana

**Comment by Poeschl** [comment]
I'm using the same port as the default port of the regular `ICantBelieveItsNotValetudo` for consistency.
The external port can be changed on the plugin page, if I'm not wrong?

**Comment by bbbenji** [comment]
Understandable.

That right, I just changed the port on the plugin page to fix the issue.
