### ISSUE TITLE
MaryTTS: No voice available for locale 'de'

### ISSUE THREAD

**Issue by markus1540** [Poeschl/Hassio-Addons#52]
**Which addon?**
MaryTTS

**Describe the bug**
Despite the addon description listing support for the locales "de, en, fr, ìt, lb, ru, sv, te and tr", no other voice than "cmu-slt-hsmm en_US female hmm" is available.

**To Reproduce**
http://your-home-assistant-instance.local:59125/process?INPUT_TEXT=Hallo+Welt&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&AUDIO=WAVE_FILE&LOCALE=de

![image](https://user-images.githubusercontent.com/2098025/75117793-faac1c80-5674-11ea-9765-3caf63ee1dc6.png)

**Comment by Poeschl** [comment]
Will look into it this week.
