### ISSUE TITLE
valetudo mapper problem home assistant core

### ISSUE THREAD

**Issue by roberdlv** [Poeschl/Hassio-Addons#58]
Hello friends, I have roborock s50, I installed Valetudo RE, it works in HA as MQTT, but the maps part does not work and I am not able to make it work, try this configuration:

I will try to put the steps that I have followed to see if I do something wrong or something is missing …

Copy the inside https://github.com/Poeschl/Hassio-Addons/tree/master/valetudo-mapper of this repository to / docker / homeassistant / custom_components / valetudo-mapper /

Config.json valetudo-mapper:

{
“mqtt”: {
“identifier”: “rockrobo”,
“topicPrefix”: “valetudo”,
“autoconfPrefix”: “homeassistant”,
“broker_url”: “mqtt: // admin: pass@192.168.1.2: 1883”,
“caPath”: “”,
“mapSettings”: {
“drawPath”: true,
“drawCharger”: true,
“drawRobot”: true,
“drawForbiddenZones”: true,
“drawVirtualWalls”: true,
“border”: 2,
“scale”: 4,
“gradientBackground”: true
},
“mapDataTopic”: “valetudo / rockrobo / map_data”,
“minMillisecondsBetweenMapUpdates”: 10000,
“publishMapImage”: true,
“publishMapData”: true
}
}

config.json roborock:

root @ rockrobo: / mnt / data / valetudo # nano config.json
GNU nano 2.2.6 File: config.json

{
“spots”: [],
“areas”: [],
“ztimers”: [],
“mqtt”: {
“enabled”: true,
“identifier”: “rockrobo”,
“topicPrefix”: “valetudo”,
“autoconfPrefix”: “homeassistant”,
“broker_url”: “mqtt: // admin: pass@192.168.1.2”,
“provideMapData”: true,
“mapSettings”: {
“drawPath”: true,
“drawCharger”: true,
“drawRobot”: true,
“border”: 2,
“scale”: 4
},
“caPath”: “”

Configuration.yaml

discovery: true
discovery_prefix: homeassistant

sensor:

platform: mqtt
state_topic: “valetudo / rockrobo / state”
json_attributes_topic: “valetudo / rockrobo / map_data_parsed”
name: xiaomi_map
value_template: ‘OK’
scan_interval: 5
remember:
exclude:
entities:
- sensor.xiaomi_map

I add custom card:

crop:
bottom: 0
left: 0
right: 0
top: 0
entity: sensor.xiaomi_map
min_height: 0
rotate: 0
type: ‘custom: valetudo-map-card’

I tried to create docker but it gives exec error user process caused “exec format error”
I use Portainer and docker from:

Pure Home Assistant (not HASSIO)
MQTT
PORTAINER
etc…

**Comment by Poeschl** [comment]
Hi there,
the Valetudo-Mapper as well as all folders inside this repository are no custom components for Homeassistant-Core. They are [addons for Homeassistant](https://www.home-assistant.io/addons/) (former HASSIO).

Since they use custom docker images specially prepared for the Home Assistant supervisor they can't be used with a pure Home Assistant Core installation out of the box.

**Comment by roberdlv** [comment]
so how could i install?  would a docker in portainer be possible?  There are not many instructions of how and it gives me error all the time.

Enviado desde mi iPhone

El 28 mar 2020, a las 23:37, Markus Pöschl <notifications@github.com> escribió:


Hi there,
the Valetudo-Mapper as well as all folders inside this repository are no custom components for Homeassistant-Core. They are addons for Homeassistant<https://www.home-assistant.io/addons/> (former HASSIO).

Since they use custom docker images specially prepared for the Home Assistant supervisor they can't be used with a pure Home Assistant Core installation out of the box

**Comment by Poeschl** [comment]
You have to create your own Dockerfile for that.
As starting point use the one from my repository and change the base image to `alpine:3.11`, after building map your `config.json` for the mapper to `/app/config.json` inside the container and open port `3000` to access the generated image.

**Comment by Poeschl** [comment]
I will also close this ticket since it's not related to the supervisor addon in any way.

**Comment by roberdlv** [comment]
Can you give me more detailed information on the steps to follow? or can you update your repository with the instructions? there are many of us who have this problem with not being able to create a docker and having problems with it because the instructions are scarce or bad.

thanks frined.

**Comment by roberdlv** [comment]
where can you help me?

________________________________
De: Markus Pöschl <notifications@github.com>
Enviado: domingo, 29 de marzo de 2020 10:45
Para: Poeschl/Hassio-Addons <Hassio-Addons@noreply.github.com>
Cc: roberdlv <rober1989_cs@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [Poeschl/Hassio-Addons] valetudo mapper problem home assistant core (#58)


Closed #58<https://github.com/Poeschl/Hassio-Addons/issues/58>.

**Comment by roberdlv** [comment]
where can you help me?

**Comment by Poeschl** [comment]
For how to build your own docker container please consult the docker documentations.
With that and the [comment above](https://github.com/Poeschl/Hassio-Addons/issues/58#issuecomment-605604231) you should be able to do it for yourself.

There will be no instructions at this repository for building plain docker containers since it's primary goal is the Home Assistant supervisor addon system.
