### ISSUE TITLE
failed to setup inotify handler

### ISSUE THREAD

**Issue by DirkTas67** [Poeschl/Hassio-Addons#59]
**Which addon?**
-- Syncthing --

**Describe the bug**
-- Syncthing gives me this message(on the synthing screen): failed to setup inotify handler. --

**To Reproduce**
-- Steps to reproduce the behavior:
1. Go to 'homeassistant.local:8123/243ffc37_syncthing'
2. the message is here in yellow --

**Expected behavior**
-- this message should not appear --

**Screenshots**
-- [Schermafdruk van 2020-03-28 20-58-51](https://user-images.githubusercontent.com/30079864/77832533-22d8e080-7137-11ea-8d50-5cc1829b1d13.png)
 --

**Comment by Poeschl** [comment]
It looks like your file system on the host has a low number for the `fs.inotify.max_user_watches` kernel parameter, which handles the global number of allowed file monitoring handles.

Unfortunately this is something that can not be fixed through the addon aka the running docker container, see https://stackoverflow.com/a/57221024.
