### ISSUE TITLE
Support Ingress - Valetudo

### ISSUE THREAD

**Issue by marciogranzotto** [Poeschl/Hassio-Addons#6]
**Which addon?**
ICantBelieveItsNotValetudo

**Is your feature request related to a problem? Please describe.**
Valetudo's web interface lacks user authentication, making it impossible to expose to the Internet. That's necessary if I want to add the interface on Home Assistant's sidebar with an iframe.

**Describe the solution you'd like**
This add-on could implement HassIO's Ingress feature, auto-adding a web interface in the sidebar. I would only need to add the Valetudo Vacuum's IP in the add-on configuration.

**Comment by chaimt** [comment]
yes ingress should solve the issue

**Comment by Poeschl** [comment]
Added the ingress feature. Please try it out when the build passes and close this issue if resolved.

**Comment by marciogranzotto** [comment]
@Poeschl it works! Thanks!
