### ISSUE TITLE
Small thing - version undefined on MaryTTS and PicoTTS

### ISSUE THREAD

**Issue by Smith754** [Poeschl/Hassio-Addons#60]
**Which addon?**

PicoTTS and MaryTTS 

**Describe the bug**

Hassio shows the following before installing new versions:

 PicoTTS undefined is available
You are currently running version 1.0.4

MaryTTS undefined is available
You are currently running version 5.2-3

**To Reproduce**

**Expected behavior**

Expected a version number  :-)

**Screenshots**

**System**

* Supervisor version: 
* Host system version:

**Comment by Smith754** [comment]
Funny, now it's not showing the issue.  And,  I have the same version numbers. Maybe it was a Hassio issue.  I'll close this.

**Comment by Poeschl** [comment]
Had the same here, a few seconds ago. I refreshed the page and it was correct 😅
