### ISSUE TITLE
function

### ISSUE THREAD

**Issue by foXaCe** [Poeschl/Hassio-Addons#69]
Hello,

how to add this function please ?
wall
zone blocked

i'm use camera.rockrobo_map only

![67422498-45d8f480-f5db-11e9-8f23-b1472cfb0962](https://user-images.githubusercontent.com/290678/80304155-990f4800-87b4-11ea-9e07-9ce59bd2906a.png)

**Comment by Poeschl** [comment]
Please take a look at the official Valetudo-mapper Repository https://github.com/rand256/valetudo-mapper.

The config ist described there an its the same as in the addon.
