### ISSUE TITLE
PIPE Fifo

### ISSUE THREAD

**Issue by wullewatz** [Poeschl/Hassio-Addons#75]
**Which addon?**
MPD
**Is your feature request related to a problem? Please describe.**
I would like an audio output to /share/snpacast/fifo

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Es wäre schön wenn du bei den Einstellungen eine Auswahlmöglichkeit für den Audio Ausgang hättest, so wie in der config.json beschrieben. Da ich kein Programmierer bin, ist es für mich nicht möglich den Audio Ausgang auf eine Pipe zu legen.

**Comment by Poeschl** [comment]
Hast dazu etwas mehr Kontext?
Welche `config.json`?

**Comment by wullewatz** [comment]
Entschuldigung. Natürlich in der mpd.conf.

Da könnte ja man einen pipe Ausgang einstellen.

**Comment by wullewatz** [comment]
Klasse Sache! Das einfachste wäre ja, wenn du den Path dwr MPD.conf auf homeassistant/lokal/share/mpd umbiegen würdest. Habe auf https://www.musicpd.org/doc/html/user.html#the-configuration-file gelesen das das geht. Das ginge bestimmt am schnellsten und jeder könnte seine Konfiguration selber bearbeiten. 

-> Falls du die nächste Zeit nicht dazu kommst, könntest du mir einen Tipp geben wie ich den Pkayer als lokales Addon zum kaufen bekomme? Beim Installieren bekomme ich nur eine Fehlermeldung. Oder komme ich über Debug SSH im /etc Ordner an die mpd.conf? Danke und Grüße!
