### ISSUE TITLE
Manifest not found on Update

### ISSUE THREAD

**Issue by wullewatz** [Poeschl/Hassio-Addons#79]
Hello, Its me again. .. :-)
Thanks for your quick response, but at the install I get this error:

20-05-23 08:20:37 INFO (SyncWorker_11) [supervisor.docker.interface] Pull image poeschl/hassio-mpd-armv7 tag 1.3.0.

20-05-23 08:20:39 ERROR (SyncWorker_11) [supervisor.docker.interface] Can't install poeschl/hassio-mpd-armv7:1.3.0 -> 404 Client Error: Not Found ("manifest for poeschl/hassio-mpd-armv7:1.3.0 not found: manifest unknown: manifest unknown").

**Comment by Poeschl** [comment]
It seem that the last hiccups from GitHub also affected the build of the addon. It just restarted it.

The addon installation should work after [the build](https://travis-ci.org/github/Poeschl/Hassio-Addons/jobs/690171510) was finished successful. Please close the ticket afterwards.
