### ISSUE TITLE
[valetudo-mapper] Map in HomeKit not available

### ISSUE THREAD

**Issue by Dodoooh** [Poeschl/Hassio-Addons#89]
**Which addon?**
valetudo-mapper 

**Describe the bug**
Map in HomeKit not available

**Expected behavior**

The addon adds a camera view of the map in Home Assistant, which is also shown in the home app on my iPhone, but there is no picture or camera view available. 
I don't know if this is a bug or a feature request, but it would be nice if the "camera" would work on the iPhone.

**System**
Supervisor: 228

**Comment by Poeschl** [comment]
Can you check if the map can be accessed on your iPhone via the "Open Web UI" button on the addon page?

If it's shown there it might be an home assistant issue, if not you might create a issue at the valetudo-mapper repository. This repository just makes it available as addon.

**Comment by Dodoooh** [comment]
> Can you check if the map can be accessed on your iPhone via the "Open Web UI" button on the addon page?
> 
> If it's shown there it might be an home assistant issue, if not you might create a issue at the valetudo-mapper repository. This repository just makes it available as addon.

this works, I mean in Apple's own home app via HomeKit. Not in the Home Assistant app

**Comment by Poeschl** [comment]
I see, you want the map also in the HomeKit App. Unfortunately this is wrong repository to ask for that feature. Please try to reach out to @rand256 at https://github.com/rand256/valetudo-mapper for it.

**Comment by Dodoooh** [comment]
The thing is, it's already in HomeKit because it's indexed as a camera. 

but that's what I thought, then I'll report there.

**Comment by Kugelfang666** [comment]
sorry to reheat this discussion. Reading through it I'm assuming there was a misunderstanding since I have the same issue. 

I'm exoposing the camera item from Home Assistant to HomeKit. Hence I'm not asking for a native HomeKit feature to the companion app or this addon but rather on a solution so that exposing via HA works as intended.
