### ISSUE TITLE
[pigpio] How to connect to this addon?

### ISSUE THREAD

**Issue by ffleandro** [Poeschl/Hassio-Addons#90]
I'm having a hard time to connect to pigpio addon from another addon.
What should be the url?

Following this:
- https://developers.home-assistant.io/docs/add-ons/communication/

Should be something like `243ffc37_pigpio:8888`, but I haven't been successful.

**Comment by ffleandro** [comment]
I misread the documentation, the url should be `243ffc37-pigpio:8888`.
Do you think it's useful to add this info the the pigpio addon README?

**Comment by Poeschl** [comment]
It's a good idea to put a example in the Readme. Can you open a PR with the changes?
