### ISSUE TITLE
[ICantBeliveItsNotValetudo] add stream_source:

### ISSUE THREAD

**Issue by Kugelfang666** [Poeschl/Hassio-Addons#95]
**Which addon?**

ICantBelieveItsNotValetudo
**Is your feature request related to a problem? Please describe.**

I cannot forward the map to HomeKit:
**Describe the solution you'd like**

in order for HA being able to forward the camera stream to HomeKit the camera needs a 
```
still_image_url: 
stream_source:
```
**Describe alternatives you've considered**

**Additional context**

**Comment by Poeschl** [comment]
When the port mapping is enabled the image of the addon can be accessed via `http://<host>:<port>/api/map/image`. You can use this for your config.
