### ISSUE TITLE
Map /ssl into syncthing container

### ISSUE THREAD

**Issue by danps1** [Poeschl/Hassio-Addons#96]
**Which addon?**

Syncthing

**Is your feature request related to a problem? Please describe.**

No problem - just a feature request

**Describe the solution you'd like**

Would it be possible to also make the /ssl folder available inside the Syncthing container? My specific use case is that I have LetsEncrypt add-on requesting wildcard certificates that have validity across multiple other hosts in my environment. I'd like to then use Syncthing to automatically sync these certificate files to all the servers that need them

**Describe alternatives you've considered**

I did try to use portainer to map the volume in manually, but I don't think this is possible with a hassio addon

**Additional context**

I think this should be as simple as mapping **/mnt/data/supervisor/ssl** to **/ssl**...

![image](https://user-images.githubusercontent.com/36139437/90088360-165dc900-dd62-11ea-8145-cd98965cde8a.png)

**Comment by Poeschl** [comment]
The mapping is an easy and simple change 😉

**Comment by danps1** [comment]
I had hoped it would be! :)

**Comment by danps1** [comment]
It works brilliantly! Thanks very much. Buying you a coffee :)
